### ISSUE TITLE
No sending state animation for message

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react-native#432] opened 2020-11-16 15:11 UTC
On the latest version v2.0.2, the 'loading/sending' state of the message does not show the 'loading.gif' asset at all in the MessageList.

gz#7391

**Comment by shodgetts** [comment] 2020-11-19 00:19
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7391'>Zendesk ticket #7391</a>:<br><br>Hello. what is your Stream organization please? We'd like to reach out.

-Stephen

**Comment by vishalnarkhede** [comment] 2020-11-26 12:18
This might be related to https://github.com/GetStream/stream-chat-react-native/issues/429

**Comment by vishalnarkhede** [comment] 2020-12-05 12:18
Closing this as duplicate of #429 :)

**Closed by vishalnarkhede** 2020-12-05 12:18 UTC

**Comment by shodgetts** [comment] 2020-12-07 17:43
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/7391'>Zendesk ticket #7391</a>:<br><br>Hey,

Please upgrade to stream-chat-react-native@2.1.0. We have fixed this issue :)

Thanks,
Vishal
