### ISSUE TITLE
useAttachmentPickerContext hook was called outside the AttachmentPickerContext provider

### ISSUE THREAD

**Issue by RAzaALy** [GetStream/stream-chat-react-native#1858] opened 2022-12-08 13:43 UTC
**Describe the bug**

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo)
- react-native or expo version
- Device/Emulator (android/ios) and OS version

**To Reproduce**

**Expected behavior**

**Additional context**

**Screenshots**

**Comment by RAzaALy** [comment] 2022-12-08 13:44
![bug](https://user-images.githubusercontent.com/74565278/206461740-bf2b82b3-086a-4ee2-909a-f6297ceca8b7.png)

**Comment by vanGalilea** [comment] 2022-12-08 14:00
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Dev environment info (please complete/provide the following information):**
> 
> * Package version (stream-chat-react-native/stream-chat-expo)
> * react-native or expo version
> * Device/Emulator (android/ios) and OS version
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Additional context** Add any other context about the problem here.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.

@RAzaALy  Can you please supply us with the above info?

**Comment by RAzaALy** [comment] 2022-12-09 10:17
"react-native": "0.70.1",
 "stream-chat-react-native": "link:../../package/native-package",
 "stream-chat-react-native-core": "link:../../package"

To Reproduce Steps to reproduce the behavior:
run the following command in main directory
yarn
yarn start
yarn run android

**Comment by vanGalilea** [comment] 2022-12-20 09:15
@RAzaALy thanks for reaching out. 

To pinpoint this issue as fast as possible, we would like to ask you to share a minimalistic repo where the problem is reproduced.
The fastest way to achieve this is with the following command to create a new RN project with Stream chat in it:

`npx react-native init MyApp --template stream-chat-react-native-template`

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by vanGalilea** [comment] 2023-03-08 15:00
@RAzaALy it's been a while since we requested the following. 

I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.

**Closed by vanGalilea** 2023-03-08 15:00 UTC
Labels: Bug, Needs More Information, Needs Triaging, Awaiting API Improvement
