### ISSUE TITLE
Fix for FK issue SQLite

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1923] opened 2023-01-22 07:51 UTC
I am getting FK error when opening Chat and responding when using SQL Lite caching.

This fixes the FK issue for Channel. Please review.

https://github.com/GetStream/stream-chat-react-native/pull/1922

**Comment by vishalnarkhede** [comment] 2023-01-23 11:12
https://github.com/GetStream/stream-chat-react-native/pull/1922#issuecomment-1400160729

**Comment by billnbell** [comment] 2023-02-06 07:59
Anything / help needed for testing?

**Comment by vanGalilea** [comment] 2023-03-08 11:06
@billnbell how are you?

We still haven't managed to reproduce the error you're getting. Have you seen this error on a frequent basis?

**Comment by billnbell** [comment] 2023-03-09 03:02
Without my fix it happens all the time. But since I put in my patch no issues.

**Comment by santhoshvai** [comment] 2023-03-10 10:45
@billnbell Could you share steps of how to reproduce this?  Please explain in detail if possible.

It happens all the time for you and never to us. So we want to know what we miss.

**Comment by vanGalilea** [comment] 2023-04-05 13:50
@billnbell I'm closing this issue since we couldn't reproduce it after numerous attempts.

We will reopen this issue and triage further if you can share a reproducible clean repo where it consistently happens.

Thank you for your contribution!

**Closed by vanGalilea** 2023-04-05 13:50 UTC
Labels: Bug, Needs Triaging
