### ISSUE TITLE
Crash caused by events 'member.added' and 'member.removed' in ChannelInner of a channel with no messages

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react-native#85] opened 2019-11-12 21:27 UTC
If the active channel has no messages and a 'member.added' or 'member.removed' event occurs, ChannelInner.addToEventHistory() attempts to get the id of the last message (which is undefined), causing a crash.

**Comment by vishalnarkhede** [comment] 2019-11-22 10:22
Thanks @cenzovit for brining this up. We will address/fix this issue as soon as possible!

**Comment by vishalnarkhede** [comment] 2019-12-03 15:16
Hey @cenzovit this has now been fixed as part of `v0.3.12`

**Comment by vishalnarkhede** [comment] 2019-12-18 11:23
Hey @cenzovit, can you confirm if the issue is fixed for you, I would like to close this issue in that case. :)

Thanks

**Closed** 2020-01-29 16:28 UTC
Labels: Resolved, bug
