### ISSUE TITLE
url is modified upon display (and thus the page does not work properly)

### ISSUE THREAD

**Issue by andreibarabas** [GetStream/stream-chat-react-native#1488] opened 2022-06-17 08:43 UTC
**Describe the bug**

If you send / receive this url (all components are already url encoded)

https://hibeamapp.com/auction/d29ya3NwYWNlcy9KREJ2aTZucHJRRjdpMWtlSU0xdy9hdWN0aW9ucy9YYkdFbWJRY3dPOGZzaHlMbjF3RA%3D%3D?h=aW5zdGFncmFtOjcxODkwMjU0ODc4MDQ3NjU

but it will be automatically converted to

https://hibeamapp.com/auction/d29ya3NwYWNlcy9KREJ2aTZucHJRRjdpMWtlSU0xdy9hdWN0aW9ucy9YYkdFbWJRY3dPOGZzaHlMbjF3RA%253D%253D?h=aW5zdGFncmFtOjcxODkwMjU0ODc4MDQ3NjU

This is wrong because it re-encoded the url, transforming the **%3D** (url ended for = character) into **%253D** (double encoded)

In the db, both the Text and HTML variants are correct, so this seems to be a problem with the url component

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native@4.7.1
- react-native 
- Device/Emulator (android/ios) and OS version: both, iOS 15.5

**To Reproduce**

1. submit a text with this url https://hibeamapp.com/auction/d29ya3NwYWNlcy9KREJ2aTZucHJRRjdpMWtlSU0xdy9hdWN0aW9ucy9YYkdFbWJRY3dPOGZzaHlMbjF3RA%3D%3D?h=aW5zdGFncmFtOjcxODkwMjU0ODc4MDQ3NjU
2. See the url displayed is wrong 
3. If you tap it, you will be redirected again to a wrong url

**Expected behavior**
To show / be redirected to exactly the same url, without any extra url encoding applied

**Screenshots**
![IMG_3395](https://user-images.githubusercontent.com/2101405/174261517-dc5dca91-1210-445f-8886-6e7617e7ff1d.jpg)

**Comment by madsroskar** [comment] 2022-06-21 11:50
Thanks for reporting this, @andreibarabas. We'll have to look into avoiding double encoding the URL.

**Comment by vanGalilea** [comment] 2022-08-16 08:13
proposed solution: remove URL encoding

**Comment by khushal87** [comment] 2023-04-25 07:45
![simulator_screenshot_59399566-6532-46F0-9A6E-D38B488C503A](https://user-images.githubusercontent.com/39884168/234208970-a346ec1c-2bdd-481e-95c8-a1f979c0fadc.png)
Just tried sending it on a newer version of our SDK, and it seems the problem is solved. Can you check @vandreleal? Thanks 😄

**Comment by vanGalilea** [comment] 2023-05-12 07:48
I was verifying what @khushal87 said! Closing this issue for now 👍🏻

**Closed by vanGalilea** 2023-05-12 07:48 UTC
Labels: Bug, Needs Triaging, Awaiting Confirmation
