### ISSUE TITLE
Cannot upload images from image picker on Android

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1640] opened 2022-08-11 12:45 UTC
**Describe the bug**
Lately, uploading an image using an image picker isn't working on android.

**Dev environment info (please complete/provide the following information):**

- Latest version
- Android

**To Reproduce**

1. Open Image Picker
2. Select an Image from the image picker.
3. You will see retry button

**Expected behaviour**
The Image should be uploaded smoothly.

**Additional context**
Check for video and file picker too while fixing the issue.

**Comment by santhoshvai** [comment] 2022-09-01 13:08
Closing this as it is not reproducible. We suspect that it was because of some symlinking issues.

**Comment by caycecollins** [comment] 2022-09-14 07:11
@santhoshvai I'm having a similar issue. When I attempt to select an image from the picker, it never seems to upload and shows the retry icon. Any suggestions on debugging this?

![image](https://user-images.githubusercontent.com/8495416/190075603-64aa2b7d-ba20-4904-88a6-eda04d6c1b7a.png)

I've tested this on `5.1.0` and `5.3.0` so far with the same result

**Comment by khushal87** [comment] 2022-09-14 09:54
Hey @caycecollins, to help you with the issue, can you please reach us through our Support at [support@getstream.io](mailto:support@getstream.io). Please don't forget to share essential details about your app id, which version you are facing the problem and also the user for which you are facing the issue. This will help us address and test the app settings and issue on our end. Thanks 😄

You can put this issue/comment as a reference there and ask anyone to escalate it to React Native Team directly.

**Closed** 2022-09-20 08:38 UTC
Labels: Bug, Needs Triaging

**Comment by khushal87** [comment] 2022-09-20 08:42
Closed since this is been handled on Zendesk.

**Comment by caycecollins** [comment] 2022-09-20 16:16
thanks @khushal87!

To followup with the solution for others who find this, the problem was that I didn't have the following permissions configured in my `AndroidManifest.xml`:

```xml
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
```

I looked through the getstream documentation again (and additional configuration / steps from the required dependencies) but didn't see anything regarding this permission. I've requested that the getstream team add this to their additional steps for react-native installations.

**Comment by santhoshvai** [comment] 2022-09-20 17:05
Hey @caycecollins, Many thanks for the followup. Can you inform us your android app's target-SDK, we want to clarify this in our documentation with details.

**Comment by caycecollins** [comment] 2022-09-20 17:10
@santhoshvai sure, here's what's in my `build.gradle`:

```groovy
    ext {
        buildToolsVersion = '31.0.0'
        minSdkVersion = 28
        compileSdkVersion = 31
        targetSdkVersion = 31
        if (System.properties['os.arch'] == 'aarch64') {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = '24.0.8215888'
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = '21.4.7075529'
        }
        googlePlayServicesAuthVersion = '19.2.0'
        kotlinVersion = '1.7.0'
    }
```

**Comment by tj-mc** [comment] 2024-01-10 06:53
In my case I patched this myself. The content type is incorrect when uploading image on Android.
It is "image" but it needs to be "image/jpg".

In stream-chat/dist/browser.js I changed this line to have the content type hardcoded.

var data = addFileToFormData(uri, name, 'image/jpg');
