### ISSUE TITLE
Typing in chat freezes the app on Android

### ISSUE THREAD

**Issue by gregssdev** [GetStream/stream-chat-react-native#1810] opened 2022-11-15 17:02 UTC
**Describe the bug**
On Android when you type some message, a long message it will freeze the app at a random interval of time

**Dev environment info (please complete/provide the following information):**
- Package version (stream-chat-react-native): 5.0.0
- react-native: 0.66.3
- Device/Emulator: Android (Any)

**To Reproduce**
1. Go to Message Input
2. Type something random around 100-200 words
3. If the app didn't freeze, clear a few words and start typing again for a while
4. App will freeze

**Expected behavior**
App should run smoothly

**Comment by billnbell** [comment] 2022-11-18 19:07
Is there a limit in SQLite or in Android ?

**Comment by vishalnarkhede** [comment] 2022-11-18 19:56
limit for?

**Comment by vishalnarkhede** [comment] 2022-11-18 20:04
@billnbell what props are you passing the Channel component? Could you show me some code?

**Comment by billnbell** [comment] 2022-11-19 04:00
I am not having any issues @gregssdev is

**Comment by vishalnarkhede** [comment] 2022-11-19 08:44
@gregssdev ping

**Comment by gregssdev** [comment] 2022-11-19 14:54
I used these props

            AutoCompleteSuggestionItem
            AutoCompleteSuggestionHeader
            channel
            disableKeyboardCompatibleView
            DateHeader
            deletedMessagesVisibiltyType
            doMarkReadRequest
            forceAlignMessages
            giphyEnabled
            hasFilePicker
            InlineUnreadIndicator
            InputButtons
            mentionAllAppUsersEnabled
            mentionAllAppUsersQuery
            MessageFooter
            MessageSimple
            MessageStatus
            MessageSystem
            ReactionList
            Reply
            SendButton
            ScrollToBottomButton
            SendMessageDisallowedIndicator
            supportedReactions
            TypingIndicator

**Comment by vishalnarkhede** [comment] 2022-11-20 12:57
It's hard to point out without looking at the implementation of these props. But I can give few tips:

- Avoid using `ChannelContext` on message level custom components e.g, MessageSimple, MessageStatus etc
- Avoid passing inline functions as custom component or inline objects/arrays as props
- You might need to do some profiling using Flipper to check if there is any particular component causing overhead for the app

**Comment by 1987cr** [comment] 2022-11-21 12:43
Maybe related to this https://github.com/facebook/react-native/issues/35350?

**Comment by vishalnarkhede** [comment] 2022-11-21 13:25
hmm interesting....

**Comment by hannojg** [comment] 2022-11-22 09:52
Does it happen for you guys on _any_ android version? For us this issue only happens on android 13 (aka. API 33(

**Comment by atsss** [comment] 2022-12-05 11:06
Any updates on it? We're also struggling with freezing chat only on Android.

**Comment by santhoshvai** [comment] 2022-12-06 11:23
@atsss @gregssdev I guess both of you are running android 13 (aka. API 33) ?

**Comment by atsss** [comment] 2022-12-06 13:37
Yes. It's happening on android 13.

**Comment by Eigilak** [comment] 2022-12-15 12:12
Same. We only experience this on 33 aka Pixel devices! 
We are on 0.70.5

**Comment by vanGalilea** [comment] 2022-12-20 09:27
Hey guys, this is a known RN/Android issue, and we're still awaiting [it](https://github.com/facebook/react-native/issues/35350) that was closed.

**Comment by nathancoleman** [comment] 2023-01-26 02:01
Is there any sort of workaround for this? Chat is basically unusable for our impacted users on Android.

**Comment by billnbell** [comment] 2023-01-26 02:11
What version are you using ?

**Comment by billnbell** [comment] 2023-01-26 02:13
What I meant by limit is: 200 words being stored in SQLite might his a 64K limit. Also there might be a limit in the REST call back to Getstream. Did you try this on IOS? Does it do the same thing?

Also, can you set an input limit to like like 2K or something?

**Comment by billnbell** [comment] 2023-01-26 02:23
Can someone submit a repo that is small so we can see it? Something like an app.tsx, and <Chat> ?

**Comment by vanGalilea** [comment] 2023-02-01 11:18
> Can someone submit a repo that is small so we can see it? Something like an app.tsx, and Chat ?

The fastest way to achieve that is with the following command to create a new RN project with Stream chat in it: 

`npx react-native init StreamChatApp --template react-native-stream-chat-template`

More information about how to run the template after initialization can be found [here](https://github.com/GetStream/react-native-stream-chat-template#react-native-stream-chat-template)

**Comment by atsss** [comment] 2023-02-06 16:33
Do you have any plans to fix the problem like that temporarily? Because our android customer is having difficulties with typing and it's so critical for chatting.
> https://github.com/facebook/react-native/issues/35350#issuecomment-1317465434

**Comment by vanGalilea** [comment] 2023-02-07 10:35
This is not a proper solution, but you can think about the following fix until RN introduces an official fix

You can patch React Native and create your inverted flat list containing the right styling. More info in this [PR](https://github.com/Expensify/App/pull/12820).

After creating your new and improved FlatList, you can pass it to Channel under the [prop FlatList](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#flatlist).

One BIG drawback is that bi-directional lazy loading will not work anymore.

We keep on monitoring this issue here and, will think along when a proper solution will be introduced.

**Comment by nathancoleman** [comment] 2023-02-08 23:14
@vanGalilea is there any workaround that can happen in the stream-chat-react-native library so that we're not having to patch React Native and create custom components? We're paying a large amount of money for Stream every month, and our Android users are having a horrible experience. I realize the root issue is outside of this project; however, that doesn't change the fact that we're paying for a broken product right now.

**Closed** 2023-02-10 15:02 UTC
Labels: Android Only

**Comment by nathancoleman** [comment] 2023-02-10 15:12
So excited to consume that workaround @santhoshvai, thanks!

**Comment by santhoshvai** [comment] 2023-02-10 15:16
Hey everyone, We have released a workaround in `5.11.0-beta.2`. Can anyone please upgrade to that version and try it out. If confirmed, we will release it to stable. This workaround seemed to work in our pixel 7 device, but we would like confirmation from users before releasing it.

**Comment by santhoshvai** [comment] 2023-02-10 15:18
@nathancoleman 😊  Please try the workaround and report if it works please. We have also contacted other customers to try it out and we intend to ship this to stable asap.

**Comment by nathancoleman** [comment] 2023-02-10 16:04
@santhoshvai I've confirmed that I can no longer reproduce the issue on my Pixel 4a with the beta release installed 💯
