### ISSUE TITLE
Images sent preview not working.

### ISSUE THREAD

**Issue by Marcoo09** [GetStream/stream-chat-react-native#845] opened 2021-09-12 15:22 UTC
**Describe the bug**
We're having a problem with the image attachments in one of our apps.
We have two get stream apps:
A production app located on Dublin and a Qa App located on Us East.
The code of both apps in the React Native application is the same, both are built on release mode.
In the QA App the image attachments are working but on Prod App not. Is it something missing on get stream apps side? (The configuration of Image upload are the same on both get stream apps)

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native: 3.7.2
- react-native: 0.63.3
- Device/Emulator (android/ios) and OS version: IOS 14.7

**To Reproduce**

1. Go to a channel
2. Attach and image
3. Image not able to be seen after sent, it could be seen when it is on the message input

**Expected behavior**
The image sent should be seen on both apps.

gz#15040

**Comment by streamiosupport** [comment] 2021-09-13 03:11
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/15040'>Zendesk ticket #15040</a>:<br><br>Hi

Thanks for the details.
Sorry, this is not a bug and I have replied to your request received via support@getstream.io. We will discuss this further through emails.
Sorry, I am closing this request as the issue section of this Github repo is now reserved only for bug reports, feature improvements, and suggestions.

Thanks for your understanding.

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Closed** 2021-09-13 11:58 UTC
