### ISSUE TITLE
Realtime is not working

### ISSUE THREAD

**Issue by hongsa** [GetStream/stream-chat-react-native#48] opened 2019-08-09 07:03 UTC
react-native: 0.59.10
stream-chat-react-native: 0.1.17
@react-native-community/netinfo: 2.0.7

`
<SafeAreaView>
        <Chat
          style={theme}
          client={chatClient}
        >
          <Channel
            client={chatClient}
            channel={channel}
          >
            <View style={{ display: 'flex', height: '100%' }}>
              <MessageList />
              <MessageInput />
            </View>
          </Channel>
        </Chat>
      </SafeAreaView>
`

In this screen,
Sending message is working.
But, if other sender send to me, it is not working to me at real time.
If I back and into screen, it is appear.

And, after sending message, below warning is appear.
I think this is related issue

Please help!!
We will use this chatting solution by enterprise.
Buy why doesn't it work????
<img width="343" alt="스크린샷 2019-08-09 오후 1 58 18" src="https://user-images.githubusercontent.com/8157631/62760453-381cd400-baae-11e9-9e35-7b7dc7a5030f.png">

**Comment by vishalnarkhede** [comment] 2019-08-12 11:35
Hey @hongsa ,

Can you share a bit more code on how you have initialized client and created the channel? That will help us with debugging.

**Comment by hongsa** [comment] 2019-08-12 12:58
` const channelId = `${targetClazz.id}-${teacher.id}-${parent.id}`;
    const conversation = await chatClient.channel('messaging', channelId, {
      name: `${teacher.name} / ${parent.name}`,
      image: targetClazz.profile_image,
      members: [userInfo.id, receiver.id],
      clazz: {
        name: targetClazz.name,
        profile_image: targetClazz.profile_image,
      },
    });`
await conversation.watch();


Only watch channel.
Anything I have to do??

**Comment by vishalnarkhede** [comment] 2019-08-13 11:21
Hey @hongsa ,

It's quite hard to say whats going wrong here. But we have some debug/logging capabilities on JS client. 

When you initialize the client, please pass the logger function as part of options object (3rd parameter):
e.g.,

```js
const chatClient = new StreamChat('qk4nn7rpcn75', null, {
  logger: (type, msg) => {
    console.log(msg);
  }
});
```

This shall log all the activities in js client. Please check this for more details about `logger` function. - https://github.com/GetStream/stream-chat-js/blob/master/src/client.js#L106

You can enable remote debugger and fetch the logs in console of browser.  If you can paste those logs here, that would be great. That will help us to check if something is failing for your case.

**Note** Make sure to send a message on channel to get the logs of those events as well.

**Comment by hongsa** [comment] 2019-08-13 15:38
sender
<img width="699" alt="스크린샷 2019-08-13 오후 10 37 04" src="https://user-images.githubusercontent.com/8157631/62955281-f5932880-be1a-11e9-8e76-c7665da32f05.png">

receiver
<img width="709" alt="스크린샷 2019-08-13 오후 10 37 11" src="https://user-images.githubusercontent.com/8157631/62955289-f926af80-be1a-11e9-80cf-2f328feb5557.png">

**Comment by vishalnarkhede** [comment] 2019-08-14 09:09
@hongsa 

Thanks. Ok so from the logs I can see that, you are receiving the `message.new`event. So there is no issue with watching the channel.

Is it possible for you to paste entire piece of code (related to stream ... you can leave api_key and secret keys blank) here or send us via email?

**Comment by hongsa** [comment] 2019-08-14 15:02
chatting container
 
import React, { Component } from 'react';
import { View, SafeAreaView } from 'react-native';
import PropTypes from 'prop-types';
import {
Chat,
Channel,
MessageList,
MessageInput,
} from 'stream-chat-react-native';
import { Navigation } from 'react-native-navigation';

import { chatClient } from '~/utills/stream';
import { popScreen } from '~/utills/router';

const theme = {
colors: {
primary: '#00c896',
},
};

class ChatConversationContainer extends Component {
constructor(props) {
super(props);
Navigation.events().bindComponent(this);
}

componentDidMount() {
Navigation.mergeOptions(this.props.componentId, {
topBar: {
leftButtons: [{
id: 'close',
icon: require('~/assets/navigation/ic_arrow_back.png'),
}],
},
});
}

async navigationButtonPressed({ buttonId }) {
if (buttonId === 'close') {
const { navigatorProps: { isCreate = false, chatListComponentId }, componentId } = this.props;
if (isCreate) {
Navigation.popTo(chatListComponentId);
}
popScreen({ componentId });
}
}

render() {
const { navigatorProps: { channel } } = this.props;
return (
<SafeAreaView>
<Chat
style={theme}
client={chatClient}
>
<Channel
client={chatClient}
channel={channel}
>
<View style={{ display: 'flex', height: '100%' }}>
<MessageList />
<MessageInput />
</View>
</Channel>
</Chat>
</SafeAreaView>
);
}
}

ChatConversationContainer.propTypes = {
componentId: PropTypes.string.isRequired,
navigatorProps: PropTypes.shape({
channel: PropTypes.object.isRequired,
isCreate: PropTypes.bool,
chatListComponentId: PropTypes.object,
}).isRequired,
};

export default ChatConversationContainer;
 
 
 
 
 
-----Original Message-----

**Comment by vishalnarkhede** [comment] 2019-08-15 11:44
Hey @hongsa ,

Did you remove the code?

**Comment by hongsa** [comment] 2019-08-15 12:10
I sent you by email!

**Comment by hongsa** [comment] 2019-08-15 12:18
Re send

```
import React, { Component } from 'react';
import { View, SafeAreaView } from 'react-native';
import PropTypes from 'prop-types';
import {
  Chat,
  Channel,
  MessageList,
  MessageInput,
} from 'stream-chat-react-native';
import { Navigation } from 'react-native-navigation';

import { chatClient } from '~/utills/stream';
import { popScreen } from '~/utills/router';

const theme = {
  colors: {
    primary: '#00c896',
  },
};

class ChatConversationContainer extends Component {
  constructor(props) {
    super(props);
    Navigation.events().bindComponent(this);
  }

  componentDidMount() {
    Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        leftButtons: [{
          id: 'close',
          icon: require('~/assets/navigation/ic_arrow_back.png'),
        }],
      },
    });
  }

  async navigationButtonPressed({ buttonId }) {
    if (buttonId === 'close') {
      const { navigatorProps: { isCreate = false, chatListComponentId }, componentId } = this.props;
      if (isCreate) {
        Navigation.popTo(chatListComponentId);
      }
      popScreen({ componentId });
    }
  }

  render() {
    const { navigatorProps: { channel } } = this.props;
    return (
      <SafeAreaView>
        <Chat
          style={theme}
          client={chatClient}
        >
          <Channel
            client={chatClient}
            channel={channel}
          >
            <View style={{ display: 'flex', height: '100%' }}>
              <MessageList />
              <MessageInput />
            </View>
          </Channel>
        </Chat>
      </SafeAreaView>
    );
  }
}

ChatConversationContainer.propTypes = {
  componentId: PropTypes.string.isRequired,
  navigatorProps: PropTypes.shape({
    channel: PropTypes.object.isRequired,
    isCreate: PropTypes.bool,
    chatListComponentId: PropTypes.object,
  }).isRequired,
};

export default ChatConversationContainer;

```

**Comment by hongsa** [comment] 2019-08-15 15:59
I solve this problem...
In chat screen, I need to get channel again by query!!!

Why example is give to params??
This is not working in real time.

Please update your example

**Comment by vishalnarkhede** [comment] 2019-08-15 16:09
Hey @hongsa 

You shouldn't need to query the channel again actually. I have a suspicion that something is going wrong when you pass the channel via param to Channel screen. In our examples we use `react-navigation` (which still works). But in your case, you are using `react-native-navigation`. 

I tried to do the setup for `react-native-navigation` library in our app example, just to test it out. But I am having some issues

I will update you once I manage to set it up and test your use case !! But great to hear that you have found a workaround for now :)

**Comment by vishalnarkhede** [comment] 2019-08-16 15:43
@hongsa So I managed to setup the example with `react-native-navigation` and reproduced the issue about real time. As it turns out, when props are passed as parameters, they get totally modified. All the immutables properties and ws connections are disturbed. So yeah ... for now you will have to query the channels when u open channel screen. This is not the case for `react-navigation` though.

**Comment by vishalnarkhede** [comment] 2019-08-17 07:33
Closing this issue for now. Solution would be to just pass channel id via params and then query the channel corresponding to channel id on channel screen.

**Closed by vishalnarkhede** 2019-08-17 07:33 UTC
