### ISSUE TITLE
Encountered two children with the same key in channel list

### ISSUE THREAD

**Issue by philippeauriach** [GetStream/stream-chat-react-native#901] opened 2021-10-04 19:19 UTC
**Describe the bug**
A user with a lot of channels (> 50) gets weird channels displayed (using `ChannelList`) after scrolling a bit (he reported the bug as "conversation duplicated). Investigating in dev mode, it appears that channels pagination is working weirdly, and returning conversation already present, resulting in duplicates in the displayed list. I added logs in "usePaginatedChannels" line 90 (`setNewChannels`) and it shows the duplicated results after having scrolled a bit (starting on the third or fourth call). I tried with a limit of 5, 10 and 30, and everytime I end up with duplicates after having scrolled.

**Dev environment info (please complete/provide the following information):**

```
const sort: ChannelSort = { last_message_at: -1 }
const options: ChannelOptions = { limit: 30 }
```
(I noticed that if I set an empty sort object, the bug does not appear)
- Package version stream-chat@4.2.0 stream-chat-react-native@3.8.3 
- react-native@0.64.1
- Device/Emulator (android/ios) and OS version iOS and Android 

**To Reproduce**

Create an UI using provided chat components, with a user having a lot of channels. Scroll for a bit, in dev mode you'll see the react warnings. 

**Expected behavior**

**Additional context**

**Screenshots**

gz#15572

**Comment by vishalnarkhede** [comment] 2021-10-05 08:46
Hey @philippeauriach We have seen this issue, and the root cause in most of the cases was the `sort`. If the `last_messages_at` field on channel is null (basically empty channel), then our backend won't be able to sort those channels appropriately. So you should

- EITHER replace last_message_at sort param with `{ last_updated: -1 }`, which is also a default sort for channels api. So for this case you simply remove the sort prop from ChannelList component
- OR add secondary sort parameter to sort null values of last_message_at field, as shown in following code snippet:
 
```tsx
sort={[
 { last_message_at: -1 },
 { cid: -1 }
]}
```

Please let me know if this helps and works :)

**Comment by philippeauriach** [comment] 2021-10-05 09:22
Hello @vishalnarkhede , we ended up removing the sort and it is working fine. Does the "last_updated" is also updated when a new message is sent in the channel ?

**Comment by vishalnarkhede** [comment] 2021-10-05 09:28
Hey @philippeauriach yes, thats correct.

**Comment by vishalnarkhede** [comment] 2021-10-05 09:28
I am closing this issue for now, but let us know if you have any more questions.

**Comment by philippeauriach** [comment] 2021-10-05 09:28
Perfect, thanks for the help !

**Closed by vishalnarkhede** 2021-10-05 09:28 UTC
Labels: question, needs triaging
