### ISSUE TITLE
App crash on deleting emoji from message input on android

### ISSUE THREAD

**Issue by datvudang** [GetStream/stream-chat-react-native#1988] opened 2023-02-26 18:01 UTC
**Describe the bug**
When the user adds the emoji with the help of numbers like '9:11' and deletes the emoji, then the app gets crashes.

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native 5.11.2
- react-native: 0.70.6
- Emulator: Android Pixel 6 API 33
- or Real device: Realme GT master - OS: Android v12

**To Reproduce**
1. Open chat, and start typing
2. Enter any time format say 9:11 and select any emoji from the list.
3. Now try to delete this emoji from the field.

**Expected behavior**
The user should be able to add and clear the emoji in the input field without any failure with help of numbers like '9:11'.

**Additional context**
- Happen when using the keyboard of the simulator.
- Use the keyboard of the MacBook or PC didn't get crash.

**Comment by khushal87** [comment] 2023-03-01 05:19
Thanks for reporting this bug, @datvudang. We were successfully able to reproduce this bug on android devices when using the keyboard, as you mentioned. Thanks for being specific. We will try to find a fix for this and get back to you soon.

**Comment by santhoshvai** [comment] 2023-11-14 13:02
@datvudang I am closing this because its not reproducible anymore. Please feel free to reopen if it's still relevant.

**Closed by santhoshvai** 2023-11-14 13:02 UTC
Labels: Bug, Android Only
