### ISSUE TITLE
Getting token not there? 

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#2160] opened 2023-06-23 09:40 UTC
Latest.

 LOG  9:37:12 AM | ERROR : {"code":5,"StatusCode":401,"message":"WS failed with code 5 and reason - Connect failed with error: \"token missing\"","isWSFailure":false}

I am passing the token.

**Comment by billnbell** [comment] 2023-06-23 18:42
I think this may be because React Native 0.72 is not supported yet. It works on Android on 0.72 but not on IOS.

**Comment by ertucaglar** [comment] 2023-06-25 02:01
I also get a similar error, but I remember using it without problems after updating to version 0.72.0

{"code":5,"StatusCode":401,"message":"WS failed with code 5 and reason - JWTAuth error: token contains an invalid number of segments","isWSFailure":false}

**Comment by billnbell** [comment] 2023-06-25 17:06
What could the issue be? I downgraded to 0.71.11 and it works fine. I do not get this error anymore when using 0.71.11.

**Comment by billnbell** [comment] 2023-06-25 19:38
OK here is some of the errors in RN 0.72.0. 

getInstance:

```
 LOG  7:30:24 PM | INFO : info connection:_connect() - waiting for token 
{
  "tags": [
    "connection"
  ]
}
 LOG  7:30:24 PM | INFO : info connection:_connect() - Connecting to wss://chat.stream-io-api.com/connect?json=<removed keys>&X-Stream-Client=stream-chat-javascript-client-browser-8.6.0 
{
  "tags": [
    "connection"
  ],
  "wsURL": "wss://chat.stream-io-api.com/connect?json=<removed keys>&X-Stream-Client=stream-chat-javascript-client-browser-8.6.0",
  "requestID": "51444967-3175-4b06-be92-ea8a2fsdsdsddss"
}
```

connectUser:
```
LOG  7:30:25 PM | INFO : info connection:onopen() - onopen callback 
{
  "tags": [
    "connection"
  ],
  "wsID": 1
}
 LOG  7:30:25 PM | INFO : info connection:onmessage() - onmessage callback 
{
  "tags": [
    "connection"
  ],
  "event": {
    "isTrusted": false,
    "data": "{\"error\":{\"StatusCode\":401,\"code\":5,\"details\":[],\"duration\":\"0\",\"message\":\"Connect failed with error: \\\"token missing\\\"\",\"more_info\":\"https://getstream.io/chat/docs/api_errors_response\"}}"
  },
  "wsID": 1
}
 LOG  7:30:25 PM | INFO : warn connection:_errorFromWSEvent() - WS failed with code 5 
{
  "tags": [
    "connection"
  ],
  "event": {
    "error": {
      "StatusCode": 401,
      "code": 5,
      "details": [],
      "duration": "0",
      "message": "Connect failed with error: \"token missing\"",
      "more_info": "https://getstream.io/chat/docs/api_errors_response"
    }
  }
}
```

**Comment by billnbell** [comment] 2023-06-25 19:39
and yes I am sending token, etc. Just like in 0.71... But in 0.72 it fails.

**Comment by dannyBies** [comment] 2023-06-25 21:07
I believe this is an issue with react-native 0.72 iOS, see https://github.com/facebook/react-native/issues/38012

**Comment by vanGalilea** [comment] 2023-06-26 02:51
Closing as the issue is caused by React Native (SocketRocket)

**Closed by vanGalilea** 2023-06-26 02:51 UTC
Labels: Needs Triaging
