### ISSUE TITLE
Video player doesn't cover the whole screen on Android

### ISSUE THREAD

**Issue by semihcihan** [GetStream/stream-chat-react-native#1617] opened 2022-08-04 07:02 UTC
**Describe the bug**
Video component shown small on Android.

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native 4.12.0
- react-native 0.67.3
- react-native-video 5.2.0
- Device
Model name Galaxy M52 5G
Model number SM-M526BR/DS
Android version 12

I also was able to reproduce this on an emulator (Android 12). Have not tried it on an older version.

**To Reproduce**

1. Send or receive a message containing a video in chat. 
2. Tap on the thumbnail of the message containing the video to play it within the app via react-native-video (not through safari because react-native-video dependency does exist). 
3. Video component where the video is being displayed is very small (seems like oneEighth of the screen just like the variable defined in AnimatedGalleryVideo.tsx)

**Expected behavior**
Video should be playing full screen, needs to cover the whole screen just like it does on iOS. 

**Screenshots**

https://user-images.githubusercontent.com/5566381/182783200-676256df-5c58-4795-b434-56cc7a1bb73b.mp4

https://user-images.githubusercontent.com/5566381/182783237-7c77d183-5b39-46c2-bd1e-5bd231da98c5.mov

**Comment by neeraj-nh** [comment] 2022-08-10 17:01
This is easily reproducible on stream-chat-react-native 4.12.0. 

Phone: Samsung Galaxy M32S.

**Comment by vanGalilea** [comment] 2022-08-12 12:19
Duplicate of https://github.com/GetStream/stream-chat-react-native/issues/1495 to be continued there

**Closed by vanGalilea** 2022-08-12 12:19 UTC
Labels: Needs Triaging

**Comment by santhoshvai** [comment] 2022-08-12 22:05
Hi @semihcihan @neeraj-nh,

Please see https://github.com/GetStream/stream-chat-react-native/issues/1495#issuecomment-1213551868 for the solution for this.
