### ISSUE TITLE
Photos permission not properly handled

### ISSUE THREAD

**Issue by jay-s-kipl** [GetStream/stream-chat-react-native#1992] opened 2023-03-02 11:00 UTC
**Describe the bug**
User needs to restart application in order to select more photos to attach, given that they chose to “Choose Photos” instead of giving the app permissions to all of them.

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native: 5.9.0
- react-native: 0.66.5
- Device/Emulator (android/ios) and OS version: All devices and emulators/simulators

**To Reproduce**

1. Tap on attachment icon.
2. When permission popup appears, select "Select More Photos", and then select some photos, and press Done.
3. Repeat Step 1, and notice that the permissions popup doesn't appear again. If you want to select more photos, you have to kill the application, and re-open to see the permission popup again.

**Expected behavior**
Permission popup should be appear always in case of "Select Photos".

Video attached below -

https://user-images.githubusercontent.com/101381898/222409903-66589755-9475-48d6-8181-8f590f1db64e.mp4

**Comment by santhoshvai** [comment] 2023-03-06 14:16
Hey @jay-s-kipl ,

This is the expected behavior. The OS automatically prompts once per app life cycle. I am closing this issue due to that.

Reference: https://developer.apple.com/documentation/photokit/delivering_an_enhanced_privacy_experience_in_your_photos_app#3695528

However, I found a bug a that when more photos are selected in the next app life cycle, It wasn't shown. I have opened a PR for that in #1994.

If you do not like the gallery's behavior you can completely replace it with the native picker by following [this guide in our documentation](https://getstream.io/chat/docs/sdk/reactnative/guides/message-input-customization/#replacing-attachmentpicker-with-native-image-picker).

**Closed by santhoshvai** 2023-03-06 14:16 UTC
Labels: Needs Triaging
