### ISSUE TITLE
Video recordings uploaded with the React Native SDK don't render on React (web)

### ISSUE THREAD

**Issue by madsroskar** [GetStream/stream-chat-react-native#1476] opened 2022-06-15 09:44 UTC
**Describe the bug**
A video recorded on an iOS device (iPhone 13) renders correctly in the app after being uploaded, but when viewed on web (react) the video doesn't render. However, the audio does play. 

I'm creating the issue here and not in the React repo for now since I suspect it might have to do with the file type used during uploading, but I'm not sure about that. I'll move the issue if that shows to make more sense later

**Dev environment info (please complete/provide the following information):**

- Package version: stream-chat-react-native v4.7.0
- react-native version: 0.67.3
- Device: ios 15.5
- React SDK: 9.1.2

**To Reproduce**

1. record a video on device
2. upload on the device to a channel
3. try to play the video on web (react)

**Expected behavior**
Video and audio should both play

**Actual behavior**
Only the audio plays

**Comment by khushal87** [comment] 2022-06-21 06:07
Seems to work fine on my end. I tested it through TypescriptMessagingApp and the typescript example app of React Repo.

https://user-images.githubusercontent.com/39884168/174727899-0adac324-1569-491d-bb3b-b16a8cf0328c.mov

**Comment by vanGalilea** [comment] 2022-06-21 08:30
Let's compare how the iOS team is uploading the file with which file format for example.

**Comment by khushal87** [comment] 2022-12-06 06:41
It seems to work well on my side after uploading video from Android and ios devices and testing on React. Anyone's aware of a case where this was reproducible? If not, I think we can close it.

**Comment by vanGalilea** [comment] 2023-03-08 14:28
@khushal87 closing this one, I couldn't reproduce it myself as well 🤷🏻

**Closed as completed by vanGalilea** 2023-03-08 14:28 UTC
Labels: Bug, Needs Triaging
