### ISSUE TITLE
Cannot read property 'user' of undefined 

### ISSUE THREAD

**Issue by tuneerclixlogix** [GetStream/stream-chat-react-native#695] opened 2021-05-31 10:57 UTC
@vishalnarkhede 
versions:
"stream-chat": "^3.7.0",
"stream-chat-react-native": "^3.3.3",
Our users have recently faced crashes on android devices on 29th May, the crash report on crashlytics was 
![image](https://user-images.githubusercontent.com/72122766/120182372-ecf82600-c22b-11eb-8bf5-9f32e3715b25.png)
Is this something that occurred for just the time being or there are some recent changes with the user object ?

**Comment by vishalnarkhede** [comment] 2021-06-02 07:01
@tuneerclixlogix are you able to reproduce this locally?

**Comment by tuneerclixlogix** [comment] 2021-06-02 07:07
No @vishalnarkhede , this happened on 28th and 29th may with few users after that there is no record of this crash , I am not able to generate this locally.

**Comment by tsirlucas** [comment] 2021-07-16 14:52
Hey @tuneerclixlogix can you send us the whole log? Gonna check that out and try to reproduce it somehow.

When you tested locally, were you using the same versions as the ones used in the app during the reported crashes? No need to do that now I'm asking in order to check if this is already fixed in newer versions once it didnt happen anymore.

Also, do you have some more info you used to try to reproduce it? Or the only thing you have is the error report?

Would be nice to have any more information you have!

**Comment by vishalnarkhede** [comment] 2021-09-15 18:45
Closing this due to lack of activity!!

**Closed by vishalnarkhede** 2021-09-15 18:45 UTC
