### ISSUE TITLE
From background mode to live chat does not reconnect

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1918] opened 2023-01-20 00:22 UTC
Upgrading from stream-chat-react-native 5.5.1  →     5.8.0

This causes opening IOS app to not refresh/reconnect to chat right anymore.

1. Login to chat, stay on IOS mobile app on real device.
2. Put app in background
3. Go back to app - send a message from another connection, and you will not receive the chat in the mobile app

v5.5.1 works perfect.

**Comment by vanGalilea** [comment] 2023-01-20 13:01
Duplicate of https://github.com/GetStream/stream-chat-react-native/issues/1910

**Closed by vanGalilea** 2023-01-20 13:01 UTC
Labels: Needs Triaging
