### ISSUE TITLE
Issue with SQLLite on 5.4.2

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1788] opened 2022-11-08 18:29 UTC
On    
```
"stream-chat-react-native": "^5.4.2",
```

We are having error show up:

```
Error on resetting Sqlite db on GetStream disconnect Cannot read property 'user_version' of undefined
```

As a work around we turned off enableOfflineSupport. What can we do to not get this crash?

**Comment by vanGalilea** [comment] 2022-11-09 09:02
Hey, @billnbell thanks for reaching out. Which `react-native-quick-sqlite` are you using?
Make sure you're using version `4.X.X`over v5 of `react-native-quick-sqlite`.  

Our SDK is currently not compatible with `react-native-quick-sqlite` lib. new APIs.

**Comment by billnbell** [comment] 2022-11-10 06:57
Yes we are using v4.

And this is crashing the app.

**Comment by vishalnarkhede** [comment] 2022-11-14 11:05
Closing this since its a duplicate of #1724 , more discussions to be followed on that other issue.

**Closed as completed by vishalnarkhede** 2022-11-14 11:05 UTC
Labels: Needs More Information, Documentation
