### ISSUE TITLE
'undefined is not a function' issue in the Channel Component

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [GetStream/stream-chat-react-native#1390] opened 2022-05-23 01:56 UTC
**Describe the bug**
Was trying to implement the Channel page as per the documentation: My code: 
 <Chat client={streamChatClient}>
       <Channel channel={channel}>
          <MessageList />
          <MessageInput />
       </Channel>
  </Chat>
<img width="257" alt="Screenshot 2022-05-23 at 7 18 56 AM" src="https://user-images.githubusercontent.com/82080446/169728776-5b2c4572-c3b0-450a-9674-06ed49ace135.png">

**Dev environment info**
    "react-native": "0.66.4",
    "stream-chat": "^6.3.0",
    "stream-chat-react-native": "^4.4.0",
Emulator OS version Android 11.

**Expected behavior**
The Channel page should be seen without any issues.

**Screenshots**
<img width="423" alt="Screenshot 2022-05-23 at 7 25 40 AM" src="https://user-images.githubusercontent.com/82080446/169728969-7688a8b4-fe54-4d29-8e68-24f09d796828.png">

**Comment by vanGalilea** [comment] 2022-05-23 05:39
Duplicate of [1391](https://github.com/GetStream/stream-chat-react-native/issues/1391) whoopsie?

**Closed by vanGalilea** 2022-05-23 05:39 UTC
Labels: Needs Triaging
