### ISSUE TITLE
White Ghost bottom modal (Android only)

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react-native#1741] opened 2022-09-27 22:00 UTC
**Describe the bug**
We are running some E2E tests in our app and on some of them are failing because at one moment a White Ghost bottom modal appears.
It seems to be the AttachmentPicker

We are wondering if you know this issue and how to fix it.

Technically, we are wrapping an important(big) stack with the OverlayProvider and the white bottom modal comes from this Overlay

**To Reproduce**
It is hard to tell exactly when it happens but it seems related with the Keyboard. 

When the E2E script plays with the keyboard and maybe when we change some pages (different navigation header) then the white ghost modal appear.

This issue happens ONLY on ANDROID

**Expected behavior**
The OverlayProvider does not have side effect

**Screenshots**
<img width="428" alt="Screen Shot 2022-09-26 at 12 11 00 PM" src="https://user-images.githubusercontent.com/1306961/192644408-09f35f30-fb3a-4b31-a93a-714c9cb042db.png">

**Comment by GregAtFramework** [comment] 2022-09-28 07:04
Hi @neopit, this has been an issue for numerous customers over the last seven months - see #1179 and #1283. Stream have not managed to fix it, but the community have identified a workaround there that may be suitable if you are not making use of the AttachmentPicker.

**Comment by vanGalilea** [comment] 2022-10-11 08:18
Duplicate of #1179

**Closed by vanGalilea** 2022-10-11 08:18 UTC
Labels: Needs Triaging

**Comment by santhoshvai** [comment] 2022-10-19 15:20
Hi @neopit,

We have published a new beta version  [v5.4.2-beta.2](https://github.com/GetStream/stream-chat-react-native/compare/v5.4.1...v5.4.2-beta.2) that aims to fix this issue. Could you please upgrade to this version and remove the patch package to `AttachmentPicker.tsx` (if any) and see if it's fixed?

I have also asked other users here: https://github.com/GetStream/stream-chat-react-native/issues/1179#issuecomment-1284182349

**Comment by mrwatts88** [comment] 2022-12-19 18:15
Still seeing the the issue in v5.4.2-beta.2

**Comment by sraut1** [comment] 2024-08-15 05:02
@santhoshvai This issue still exist on V5.34.0

**Comment by mudassir-iqbal** [comment] 2025-10-16 12:44
Still facing this issue in v8.5.2

**Comment by chrisknepper-ef** [comment] 2025-11-20 20:54
I believe this issue is related to versions of `@gorhom/bottom-sheet` newer than 5.1.4. We are working around the issue by using `overrides` in package.json to force resolution of `@gorhom/bottom-sheet` to version 5.1.4 like this:

```
  "overrides": {
    "stream-chat-react-native-core": {
      "@gorhom/bottom-sheet": "5.1.4"
    }
  }
```
