### ISSUE TITLE
Channels shown multiple times

### ISSUE THREAD

**Issue by philippeauriach** [GetStream/stream-chat-react-native#940] opened 2021-10-19 14:14 UTC
**Describe the bug**
A single channel is shown multiple times.

`<ChannelList/>` is shown only when the user is connected to GetStream, the following way : 
```
          <ChannelList
            filters={_filters}
            options={options}
            lockChannelOrder
            LoadingIndicator={LoadingScreen}
            Preview={ChannelItem}
            loadMoreThreshold={0.9}
            HeaderNetworkDownIndicator={NullComponent}
            EmptyStateIndicator={NullComponent}
          />
```
`_filters` is the result of a useMemo, updated when we change the filters. Basically it is just `{type: 'messaging', members: {$in: [userIdentifier]}}`
`options` is static `= { limit: 30 }`
`ChannelItem` is a home made component following the documentation (consuming the channel object and returning a memoized component to display channels)

We regularly have an issue where a single channel is displayed multiple times. I'm having trouble reproducing it in dev (it happens on an end user account, I can provide a video showing the problem). 
Any tips that could explain this ? We previously had a similar problem, caused by the `sort` option, that we removed on advice from the GetStream team and it improved the situation by a lot.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo) : `stream-chat@4.2.0`, `stream-chat-react-native@3.9.0`
- `react-native@0.64.1`
- Device/Emulator (android/ios) and OS version iOS, iPhone 8 and 12

**Expected behavior**

**Additional context**
We have a server side job that sync users with conversations (to update conversation data), not sure if this could cause a problem? Should not? 

**Screenshots**

gz#15977

**Comment by madsroskar** [comment] 2021-10-19 14:49
Hi @philippeauriach, thanks for reaching out. I don't immediately know of tips, but I'll set up an app with the same version of the dependencies and test it out to try to reproduce the issue on my end.

> We have a server side job that sync users with conversations (to update conversation data), not sure if this could cause a problem?

I'm not sure I understand what's being synced in this case. Are you updating the channels with [custom data](https://getstream.io/chat/docs/javascript/channel_update/?language=javascript)? If so, it doesn't sound like it would cause the issue, but it's worth looking into - thanks! :) 

Otherwise, would you be able to explain a bit more what the sync does? 

Thank you again,
Mads

**Comment by philippeauriach** [comment] 2021-10-19 15:03
Video sent to your email, with additional info about the app purpose and how it works! thanks again

**Comment by jehartzog** [comment] 2021-11-09 22:31
We are seeing this issue also exactly the same as @philippeauriach describes. It is a rare reproduction, maybe once every 100 sessions. It often self resolves when the app is hard-killed and restarted. We could not find any way to reproduce it yet. If somebody finds the answer, we'd be happy to help test the solution and see if we can go a few weeks without any more reports of this.

**Comment by vishalnarkhede** [comment] 2021-11-10 07:20
@jehartzog what `sort` prop have you set on ChannelList component?

**Comment by jehartzog** [comment] 2021-11-10 14:11
@vishalnarkhede `const sort: ChannelSortBase = {last_message_at: -1};`

**Comment by vishalnarkhede** [comment] 2021-11-10 17:32
Hey @jehartzog please take a look at this. It should solve the issue - https://github.com/GetStream/stream-chat-react-native/issues/901#issuecomment-934199488

**Comment by jehartzog** [comment] 2021-11-11 15:19
@vishalnarkhede Thank you for the pointer. We have made the code change (removing the `sort` prop since we use default anyway). Since we saw this issue very rarely in our app and we don't have a reliable reproduction, we won't be able to confirm that this clears it anytime soon, but we'll throw a note back here if we happen to see it again.

**Comment by madsroskar** [comment] 2021-12-30 18:14
Hi @jehartzog - just wondering if you have noticed this reoccurring yet?

**Comment by jehartzog** [comment] 2021-12-31 17:19
@madsroskar I've left the project and wouldn't be a good source to answer the question. @lucaswhitman would know better if the issue has reoccurred since this change.

**Comment by lucaswhitman** [comment] 2022-01-03 17:12
@madsroskar I haven't had any reports, but they were few and far between in the first place so it's hard to say for sure.

**Comment by vishalnarkhede** [comment] 2022-03-01 09:34
I am going to close this issue for now.

On side note, we have published our next major version of RN Chat SDK - `v4.1.0` 🎉.

This release includes plenty of improvements and fixes. Please take a look at [**Release Notes**](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.1.0) for details.

**Closed by vishalnarkhede** 2022-03-01 09:34 UTC
Labels: Needs Triaging, Added To Backlog
