### ISSUE TITLE
Giphy Shuffle is broken in Thread Reply Screen

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1294] opened 2022-04-19 08:21 UTC
When you try to click on the shuffle button on the Giphy for the Thread screen, the new giphy doesn't rerender on the screen.

Ref - https://github.com/GetStream/stream-chat-react-native/issues/1266#issuecomment-1100748452

gz#21984

**Comment by vanGalilea** [comment] 2022-04-26 09:09
@khushal87 couldn't reproduce the issue

**Comment by vanGalilea** [comment] 2022-05-10 08:28
@madsroskar will share an app where this might be easy to reproduce and might have to do with shards.

**Comment by vanGalilea** [comment] 2022-05-10 08:28
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1294?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @santhoshvai @vishalnarkhede

**Comment by madsroskar** [comment] 2022-05-24 08:00
I was not able to reproduce this either - closing the issue for now.

**Closed by madsroskar** 2022-05-24 08:00 UTC
Labels: Needs Triaging
