### ISSUE TITLE
[🐛] Typescript type for DefaultStreamChatGenerics not working

### ISSUE THREAD

**Issue by rijulaggarwal16** [GetStream/stream-chat-react-native#2207] opened 2023-08-07 00:26 UTC
## Issue

I'm using typescript in my project. When I use DefaultStreamChatGenerics to initialize the stream, it initializes without complain but when I try to use it to obtain or use inside stream chat components, it complains about being incompatible types.

I use it like so:
```
import {
  Chat, DefaultStreamChatGenerics, OverlayProvider,
} from 'stream-chat-expo';

const chatClient = StreamChat.getInstance<DefaultStreamChatGenerics>(CHAT_API_KEY);
...
return (
  ...
  <Chat client={chatClient}>
  ...
  </Chat>
)
```

The typescript compiler complains as follows:
```
Type 'import("node_modules/stream-chat/dist/types/client").StreamChat<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>' is not assignable to type 'import("node_modules/stream-chat-react-native-core/node_modules/stream-chat/dist/types/client").StreamChat<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>'.
  Types of property 'activeChannels' are incompatible.
    Type '{ [key: string]: import("node_modules/stream-chat/dist/types/channel").Channel<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>; }' is not assignable to type '{ [key: string]: import("node_modules/stream-chat-react-native-core/node_modules/stream-chat/dist/types/channel").Channel<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>; }'.
      'string' index signatures are incompatible.
        Type 'import("node_modules/stream-chat/dist/types/channel").Channel<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>' is not assignable to type 'import("node_modules/stream-chat-react-native-core/node_modules/stream-chat/dist/types/channel").Channel<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>'.
          Types of property 'state' are incompatible.
            Type 'import("node_modules/stream-chat/dist/types/channel_state").ChannelState<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>' is not assignable to type 'import("node_modules/stream-chat-react-native-core/node_modules/stream-chat/dist/types/channel_state").ChannelState<import("node_modules/stream-chat-react-native-core/lib/typescript/types/types").DefaultStreamChatGenerics>'.
              Types have separate declarations of a private property 'switchToMessageSet'.ts(2322)
ChatContext.d.ts(26, 5): The expected type comes from property 'client' which is declared here on type 'IntrinsicAttributes & Pick<ChatContextValue<DefaultStreamChatGenerics>, "client"> & Partial<Pick<ChatContextValue<DefaultStreamChatGenerics>, "ImageComponent">> & { ...; } & { ...; }'
(property) client: StreamChat<DefaultStreamChatGenerics>
```

If I donot initialize with the generic like so:
`const chatClient = StreamChat.getInstance(CHAT_API_KEY);`

Typescript still complains:
```
Type 'StreamChat<DefaultGenerics>' is not assignable to type 'StreamChat<DefaultStreamChatGenerics>'.
  Types of property 'activeChannels' are incompatible.
    Type '{ [key: string]: Channel<DefaultGenerics>; }' is not assignable to type '{ [key: string]: Channel<DefaultStreamChatGenerics>; }'.
      'string' index signatures are incompatible.
        Type 'Channel<DefaultGenerics>' is not assignable to type 'Channel<DefaultStreamChatGenerics>'.
          Types of property 'state' are incompatible.
            Type 'ChannelState<DefaultGenerics>' is not assignable to type 'ChannelState<DefaultStreamChatGenerics>'.
              Types have separate declarations of a private property 'switchToMessageSet'.ts(2322)
```

### Steps to reproduce

See issue above

### Expected behavior

Typescript compiles successfully without errors

## Environment
I'm using:
"stream-chat-expo": "^5.15.3",

**Comment by vishalnarkhede** [comment] 2023-09-13 09:41
Hey @rijulaggarwal16 seems like you have installed `stream-chat` depedency explicitely in your project. You don't need to do that since it comes with `stream-chat-react-native` or `stream-chat-expo` by default. And this issue is caused by conflicting version of stream-chat in your project.

So if you simple remove stream-chat dependency from package.json and do yarn install, I think this error should go away.

I am going to close this issue for now, but please let us know if you have any other questions. Happy to reopen in case it doesn't fix the issue.

**Closed by vishalnarkhede** 2023-09-13 09:41 UTC
Labels: Needs Triaging

**Comment by riteshreg** [comment] 2024-04-04 07:20
facing same issue

**Comment by alexmlong** [comment] 2024-04-17 02:31
Same

**Comment by alexmlong** [comment] 2024-04-17 02:32
> Hey @rijulaggarwal16 seems like you have installed `stream-chat` depedency explicitely in your project. You don't need to do that since it comes with `stream-chat-react-native` or `stream-chat-expo` by default. And this issue is caused by conflicting version of stream-chat in your project.
> 
> So if you simple remove stream-chat dependency from package.json and do yarn install, I think this error should go away.
> 
> I am going to close this issue for now, but please let us know if you have any other questions. Happy to reopen in case it doesn't fix the issue.

How do you import StreamChat without the 'stream-chat' package? It's not in 'stream-chat-expo'

**Comment by alexmlong** [comment] 2024-04-17 03:00
For some reason I'm not getting this error in another project with the exact same code

**Comment by alexmlong** [comment] 2024-07-22 15:25
> > For some reason I'm not getting this error in another project with the exact same code
> 
> @alexmlong did you figure out what was going on? Running into same problem

Hey there, unfortunately I can't remember anything about this issue but I can say that I'm no longer having it. Sorry that's not very helpful 🤷‍♂️.

I read the above comments and looked at my package.json. I don't have `stream-chat` as a dep in package.json anymore, but I'm still importing it from `stream-chat`, i.e. `import { StreamChat} from "stream-chat"`. I'm not sure how that's working, unless it's still installed in my package-lock? I have version "^5.27.1" set for "stream-chat-expo". Hope that helps!

**Comment by vitorcamachoo** [comment] 2024-09-02 18:22
By having a monorepo with two applications (one web, the other native), this issue popped out. How can I have this working in a monorepo as the web depends on `stream-chat`?

**Comment by nattifnatt** [comment] 2024-09-24 09:08
I was also running into the same issue in my turborepo where I have my api and react-native code. 
I found the issue in node_modules folder in the root > stream-chat-react-native-core > package.json.
There I noticed it had dependency to stream-chat 8.39.0 but in my api/package.json I had stream-chat 8.40.9 installed.
I uninstalled 8.40.9 and added 8.39.0 in my api instead, reinstalled everything and now it works.

**Comment by Paligi** [comment] 2024-12-24 01:35
I change the version to "stream-chat-react-native": "5.43.0" and it works

**Comment by GabrielCastilloH** [comment] 2025-01-13 16:02
The error occurs because useCreateChatClient can return null before the client is created. You just need to handle the case where chatClient is null:
```
const chatClient = useCreateChatClient({
    apiKey: chatApiKey,
    userData: user,
    tokenOrProvider: chatUserToken,
  });

  **if (!chatClient) {**
    return (
      <View>
        <Text>Loading chat...</Text>
      </View>
    );
  }

  return (
    <OverlayProvider>
      <Chat client={chatClient}>
        <ChannelList />
      </Chat>
    </OverlayProvider>
  );
```
