### ISSUE TITLE
java.lang.IndexOutOfBoundsException when try to give reactions on message.

### ISSUE THREAD

**Issue by rajkapoordev** [GetStream/stream-chat-react-native#1054] opened 2021-12-16 09:12 UTC
**Describe the bug**
When try to give reaction on message in android app crash with array index out of bound. It is working good in iOS. I have checked the iMessage demo, that demo is also working good for both platform iOS/android.
`reactionsEnabled={false}`
If i turn off reactions with false as a flag then there is no crash.

**Error thrown in logcat android studio**

`java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.facebook.react.bridge.JavaOnlyArray.getDouble(JavaOnlyArray.java:91)
        at com.horcrux.svg.RenderableView.setupPaint(RenderableView.java:485)
        at com.horcrux.svg.RenderableView.setupFillPaint(RenderableView.java:435)
        at com.horcrux.svg.RenderableView.draw(RenderableView.java:373)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:339)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:104)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:339)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:304)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:255)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:106)
        at android.view.View.draw(View.java:21547)
        at android.view.View.draw(View.java:21418)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.draw(View.java:21550)
        at android.widget.ScrollView.draw(ScrollView.java:1835)
        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:475)
        at android.view.View.draw(View.java:21418)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21550)
        at android.view.View.draw(View.java:21418)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.draw(View.java:21416)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
        at android.view.View.draw(View.java:21550)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:122)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:56)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2856)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)`

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native : ^3.10.2
- react-native : ^0.63.4
- All android devices and emulator

**Step To Reproduce**

1. Go to channel screen
2. long press on message... app crash

**Expected behavior**
App should not be crash and reactions should be shown.

gz#17631

**Comment by vishalnarkhede** [comment] 2021-12-20 08:54
Hey @rajkapoordev this issue seems to be coming from [BlurView](https://www.npmjs.com/package/@react-native-community/blur) package. We have removed this dependency from the SDK in latest release [v4.0.0-beta.1](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.0.0-beta.1).

Stable release for v4 should be published within a month or so, but feel free to upgrade and test it within your application. I am going to close this issue for now.

**Comment by rajkapoordev** [comment] 2021-12-20 11:59
Hello @vishalnarkhede ,
Thank you for reply
I have already added below line in app/build.gradle
` implementation('com.eightbitlab:blurview:1.6.6')`

**Comment by rajkapoordev** [comment] 2021-12-21 09:56
Hello @vishalnarkhede ,
There is still issue in  [v4.0.0-beta.1.](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.0.0-beta.1).
In [v4.0.0-beta.1.](https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.0.0-beta.1) there is no flag `reactionsEnabled` So it is crashing when long press on message in android devices.

**Comment by vishalnarkhede** [comment] 2021-12-21 09:59
@rajkapoordev https://getstream.io/chat/docs/sdk/reactnative/4.0.0/basics/upgrading-from-v3/#reactionsenabled

**Comment by rajkapoordev** [comment] 2021-12-21 10:03
@vishalnarkhede 
```
<Channel
  overrideOwnCapabilities={{
    sendReactions: false
  }}
>
```
Above code turn off reactions correct?
But I want the reactions in my app as same as iMessage.
If you need more info please let me know.

**Comment by rajkapoordev** [comment] 2021-12-21 10:14
@vishalnarkhede ,
I think this crash because of **react-native-svg**
In a error log there is below line
`com.horcrux.svg.GroupView.draw(GroupView.java:81)`
please check all error log details in first comment.

**Comment by madsroskar** [comment] 2021-12-21 11:32
@rajkapoordev Have you added any customizations to the reactions, and/or the SVGs used? I'll try to reproduce it, and look into what's going on.

**Comment by rajkapoordev** [comment] 2021-12-21 12:06
@madsroskar , No I haven't add any specific thing
I am using javascript with 
**Dev environment info (please complete/provide the following information):**

stream-chat-react-native : ^3.10.2
react-native : ^0.63.4
All android devices and emulator


```
  {selectedChannel ? (
          <Chat client={chatClient}>
            <Channel
              channel={selectedChannel}
              keyboardVerticalOffset={StatusBar.currentHeight + headerHeight}
              myMessageTheme={myMessageTheme}
              enforceUniqueReaction={true}
              messageActions={({
                copyMessage, // MessageAction | null;
                deleteMessage,
                isMyMessage, // MessageAction | null;
                editMessage, // MessageAction | null;
              }) =>
                isMyMessage
                  ? [copyMessage, editMessage, deleteMessage]
                  : [copyMessage]
              }
            >
              <View style={StyleSheet.absoluteFill}>
                <MessageList />
                <MessageInput />
              </View>
            </Channel>
          </Chat>
        ) : !Object.keys(popupMessage).length ? (
          <View
            style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}
          >
            <ActivityIndicator size={'large'} color={overlayDark} />
          </View>
        ) : null}
```

**Comment by madsroskar** [comment] 2021-12-21 14:38
Thank you for adding the Chat and Channel component as well!

**Comment by vishalnarkhede** [comment] 2021-12-21 14:58
@rajkapoordev are you using BlurView in your application by any chance?

**Comment by rajkapoordev** [comment] 2021-12-22 04:33
@vishalnarkhede ,
I am using BlurView in the tab bar component and previously it was crash when app launch.
After adding below line in app/build.gradle this issue is fixed.
`implementation('com.eightbitlab:blurview:1.6.6')
`

**Comment by ToshKoevoets** [comment] 2021-12-29 20:38
Yes this probably an svgView issue, not blurview, have it to on certain devices, for sure android 10, but not 11 I think:



https://github.com/react-native-svg/react-native-svg/issues/948

**Comment by madsroskar** [comment] 2021-12-29 20:43
Can you try to set the color `white_snow` in the theme to something like `rgb(252, 252, 252)`? ([theming docs](https://getstream.io/chat/docs/sdk/reactnative/customization/theming/))

I think it's an issue where a hex value passed to an SVG component through `useAnimatedProps` from reanimated2 breaks, making `react-native-svg` not able to parse the color correctly 

It would be `colors: { white_snow: 'rgb(252, 252, 252)' }` for example

**Comment by madsroskar** [comment] 2021-12-29 20:48
(cc @rajkapoordev @ToshKoevoets ☝🏻 )

**Comment by madsroskar** [comment] 2021-12-29 22:01
Seems like it is a result of changes in reanimated v2.3.x, so it should also help for the time being to downgrade `react-native-reanimated` to 2.2.x

**Comment by rajkapoordev** [comment] 2021-12-31 09:01
Thank you so much @ToshKoevoets ,
It is working fine rgb(252, 252, 252). and react-native-reanimated version is "^2.2.4"

**Closed** 2021-12-31 09:19 UTC
Labels: Bug, Resolved, Awaiting New Release
