### ISSUE TITLE
[🐛] Thread reply error

### ISSUE THREAD

**Issue by krushita042023** [GetStream/stream-chat-react-native#2257] opened 2023-10-12 04:51 UTC
## Issue

when open thread screen getting this error message : StreamChat error code 4: GetReplies failed with error: "Message with id undefined doesn't exist"

![Screenshot_1697086179](https://github.com/GetStream/stream-chat-react-native/assets/129855948/5f6cce10-df84-4669-b3f5-88361d968c40)

**Comment by vishalnarkhede** [comment] 2023-10-16 11:43
Hey @krushita042023 happy to help, but these kind of issues are generally integration related issues and not directly a bug within SDK. So it would be really helpful if you can share a minimum reproducible repo with us. Please do so and get in touch with support@getstream.io. This repository is reserved for bugs within SDK only.

**Comment by enocmontiel** [comment] 2023-10-16 23:58
Hi @krushita042023 any discovery from your side? running with the same issue, I'm getting crazy!!

**Comment by krushita042023** [comment] 2023-10-17 03:48
Facing this issue after upgrading stream-chat package 8.11.0 to 8.12.3 and stream-chat-react-native package 5.17.1 to 5.18.1.

**Comment by vishalnarkhede** [comment] 2023-10-18 14:06
I would happy to help here as well, if anyone can share a min reproducible repository with us.

**Comment by vishalnarkhede** [comment] 2023-10-19 07:55
Pardon me people ... I am able to reproduce the issue now. I will get back asap

**Comment by krushita042023** [comment] 2023-10-19 09:58
here is my channel and Thread component.
 
```javascript
 <View style={{ flex: 1, backgroundColor: "white", paddingBottom: bottom }}>
            <Channel
                channel={channel}
                enforceUniqueReaction
                initialScrollToFirstUnreadMessage
                keyboardVerticalOffset={Platform.OS === 'ios' ? 60 : -300}
                messageId={messageId}
                hideStickyDateHeader={true}
                // KeyboardCompatibleView={CustomKeyboardCompatibleView}
                thread={selectedThread}
                hasFilePicker={false}
                // deletedMessagesVisibilityType='never'                    
            >
                <ChannelHeader channel={channel} subtitleText={membersStatus}
                    RightContent={() => (<RightArrowButton onPress={() => navigation.navigate("ChannelDetailsScreen", { channel, allowGroupActions })} />)}
                />
                <MessageList
                    onThreadSelect={(thread) => {
                        setSelectedThread(thread);
                        navigation.navigate('ThreadScreen', {
                            channel,
                            thread,
                        });
                    }}
                    Message={customeMessageView}
                    disableTypingIndicator={false}
                    TypingIndicator={() => (<TypingIndicator />)}            
                />
                {isReadOnlyGroup || allowToChat === 0 || allowToChat === '0' || getImpersonateMode()
                    ? null
                    :
                    <MessageInput
                        SendButton={StreamButton}
                        FileUploadPreview={CustomeFileUpload}
                    />
                }
            </Channel>
        </View >
``` 
ThreadScreen.js
```javascript
import React, { useEffect, useState } from 'react';
import { Platform, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {
    Channel,
    MessageInput,
    Thread,
    useAttachmentPickerContext,
    useTypingString,
} from 'stream-chat-react-native';
import { ChannelHeader } from './Component/ChannelHeader';
import { StreamButton } from './Component/SendButton';
import KeyboardSpacer from 'react-native-keyboard-spacer';
import syncStorage from '../../SyncStorage';
import { Text } from 'react-native';


const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
});

const ThreadHeader = ({ thread }) => {
    const typing = useTypingString();

    return (
        <ChannelHeader
            inSafeArea
            subtitleText={typing ? typing : `with ${thread?.user?.name}`}
            titleText='Thread Reply'
        />
    );
};

export const ThreadScreen = ({
    route: {
        params: { channel, thread },
    },
}) => {

    const { setSelectedImages } = useAttachmentPickerContext();
    const [allowToChat, setAllowToChat] = useState(syncStorage.get("allowToChatStream"))

    useEffect(() => {
        setSelectedImages([]);
        return () => setSelectedImages([]);
    }, []);

    return (
        <SafeAreaView style={[styles.container, { backgroundColor: "white" }]}>
            <Channel
                channel={channel}
                enforceUniqueReaction
                keyboardVerticalOffset={Platform.OS === 'ios' ? 0 : -300}
                thread={thread}
                threadList
                disableKeyboardCompatibleView
                SendButton={StreamButton}
                myMessageTheme={{
                    messageSimple: {
                        content: {
                            textContainer: {
                                backgroundColor: '#0071bc',
                                elevation: 20,
                                borderWidth: 0,
                            },
                            markdown: {
                                text: {
                                    color: 'white'
                                },
                            }
                        },
                    },
                }}
            >
                <View style={styles.container}>
                    <ThreadHeader thread={thread} />
                    <Thread
                        additionalMessageInputProps={{
                            disabled: allowToChat === 0 || allowToChat === '0' ? true : false,                            
                        }}
                    />

                    {Platform.OS === 'ios' && (
                        <KeyboardSpacer />
                    )}

                </View>
            </Channel>
        </SafeAreaView>
    );
};
```

**Comment by vishalnarkhede** [comment] 2023-10-19 10:25
I would like to apologize for closing the issue too fast earlier. I did indeed try to reproduce the issue on my local but couldn't, but that was mainly because of some local linking I had done on my local project, due to which old version of js client was being used for me on example project. 

But I have raised a PR for fix and it should be merged pretty soon. And thank you for your patience here :)

**Closed** 2023-10-19 10:31 UTC
Labels: Needs Triaging

**Comment by vishalnarkhede** [comment] 2023-10-19 11:55
The fix has been released as part of `v5.19.1`

**Comment by krushita042023** [comment] 2023-10-20 04:36
Thanks. Its working now.

**Comment by st1992** [comment] 2023-12-20 14:25
Still facing this issue inspite of updating to v5.22.1
