### ISSUE TITLE
usePaginatedChannels doesn't reload if filters change quickly

### ISSUE THREAD

**Issue by gilbertl** [GetStream/stream-chat-react-native#792] opened 2021-08-06 10:47 UTC
**Describe the bug**
usePaginatedChannels will use stale filters / sort conditions if filters change in quick succession

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native
- react-native 0.64
- Device/Emulator (android/ios): Android device

**To Reproduce**

1. Display <ChannelList >with a dynamic filter

```
const filters = useMemo(
    () => ({
      id: {
        $in: ids
      },
    }),
    [ids]
  )
```
2. Trigger a changes to ids in quick succession
```
ids.push('x')
ids.push('y')
```

Notice that 'x' would be reflected in the channels but not y.

Adding a print statement to this line suggests the reload is getting skipped because "loadingChannels" is true

https://github.com/GetStream/stream-chat-react-native/blob/9e742476082a80c9b25b42117bbb1d69a2b2b63a/package/src/components/ChannelList/hooks/usePaginatedChannels.ts#L64

**Expected behavior**
The channels would reflect the latest change to the filter variable

**Comment by jehartzog** [comment] 2021-08-09 16:47
Possible dup of #678. We ended up not using the `filter` prop dynamically, as it was too challenging to get the client to behave correctly. We instead use our API to add/remove users from channels as needed.

**Comment by vishalnarkhede** [comment] 2021-09-28 17:54
Closing since its a duplicate of #678 . We will pick this up soon.

**Closed by vishalnarkhede** 2021-09-28 17:54 UTC
Labels: bug
