### ISSUE TITLE
App crushes after long press on message

### ISSUE THREAD

**Issue by ChenDimri** [GetStream/stream-chat-react-native#1119] opened 2022-01-30 14:20 UTC
**Describe the bug**
When I press a long press on a message in the chat to see the actions (delete, etc),
 I see it for a second and than the app crashes

**Dev environment info (please complete/provide the following information):**

- stream-chat-react-native: 3.10.2
- react-native : 0.63.3
-  Emulator on android device

**Expected behavior**
To see the available actions for a message

gz#19000

**Comment by vishalnarkhede** [comment] 2022-02-01 09:26
@ChenDimri do you see some error in console?

**Comment by vishalnarkhede** [comment] 2022-02-01 09:26
Also do you mind sharing some code around chat components in your app?

**Comment by ChenDimri** [comment] 2022-02-01 10:02
Hi,
I don't see any error/warning in the console.
I just started using the chat so most of the code is similar to the
examples that are shown in the documantain in your website.
I have a problem with reanimated library on IOS which I'm trying to solve
with one of your colleagues. It might be related somehow?

**Comment by ben-wright** [comment] 2022-02-02 09:32
Hello, I'm also getting same issue
- stream-chat-react-native: 3.10.2
- react-native : 0.67.2

I've applied patch mentioned here: https://github.com/GetStream/stream-chat-react-native/issues/549#issuecomment-796974121
and gradle edit suggested here: https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#android-5

But still getting following native error when message actions are displayed:
```
FATAL EXCEPTION: main
    Process: com.xxx, PID: 7340
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
```

**Comment by vishalnarkhede** [comment] 2022-02-02 16:05
Hey guys, unfortunately we are not able to reproduce this issue on our side. Would you please mind setting up an example app and share it with us where we can reproduce this issue and investigate on our side?

**Comment by ao-alexi** [comment] 2022-02-03 12:50
Hi, we've had this same issue and it got fixed by downgrading react-native-reanimated to 2.2.4. hope this helps.

**Comment by gogolubev** [comment] 2022-02-03 13:04
Hi there, I have the same issue.
I've removed reactions by adding `reactionsEnabled={false}` to the Channel component and it works fine now.

**Comment by vishalnarkhede** [comment] 2022-02-03 13:17
> Hello, I'm also getting same issue
> 
> * stream-chat-react-native: 3.10.2
> * react-native : 0.67.2
> 
> I've applied patch mentioned here: [#549 (comment)](https://github.com/GetStream/stream-chat-react-native/issues/549#issuecomment-796974121) and gradle edit suggested here: https://getstream.io/chat/docs/sdk/reactnative/basics/troubleshooting/#android-5
> 
> But still getting following native error when message actions are displayed:
> 
> ```
> FATAL EXCEPTION: main
>     Process: com.xxx, PID: 7340
>     java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
> ```

@ben-wright BlurView dependency has been removed from v4 of SDK. Currently we are still in beta, but you can still use the upgrade helper guide to test it out
- Beta version - https://github.com/GetStream/stream-chat-react-native/releases/tag/v4.0.0-beta.4
- Upgrade Helper - https://getstream.io/chat/docs/sdk/reactnative/4.0.0/basics/upgrading-from-v3/

**Comment by ben-wright** [comment] 2022-02-03 17:05
Will give v4 a test at some point. Thanks @vishalnarkhede.

I can confirm downgrading to react-native-reanimated 2.2.3 also resolved our issue. Thanks

**Comment by ChenDimri** [comment] 2022-02-24 15:14
@ao-alexi worked for me, thanks!

**Closed** 2022-02-24 15:14 UTC
