### ISSUE TITLE
Android - The pictures (available for the attachment) are disappeared suddenly.

### ISSUE THREAD

**Issue by dheeraj-m-kipl** [GetStream/stream-chat-react-native#1881] opened 2022-12-29 08:28 UTC
**Describe the bug**
If there are lots of photos available on your device, and you scroll too fast to the bottom without waiting for the photos to load properly, and tap multiple times, it gets into an infinite loading state without having you know about it, thereby freezing the application entirely.

**Dev environment info**

- Package version - stream-chat-react-native - v5.6.0
- react-native version - v0.66.5
- Device/Emulator - Samsung Galaxy A31 with Android 12, Oneplus 8T with Android 12.

**To Reproduce**
1. Test on an Android device having lots of photos in the Gallery.
1. Open a channel.
2. Click on attachment icon, and select photos option.
3. Keep scrolling down very fast to the bottom, and keep tapping on a photo multiple times.
4. Notice how suddenly all the photos disappear and you see a blank white screen.

**Expected behavior**
The media picker should not make photos disappear.

**Additional context**
On some Android devices for example Samsung device, the screen becomes blank, while on some other for example OnePlus devices, the photos aren't disappeared but the loader enters into an infinite loading state, which can be observed by dragging down the attachment picker handle from top to bottom when you stop seeing the photos getting selected on tapping them.

**Video**

https://user-images.githubusercontent.com/85980805/209924283-a8fb094e-4cac-418e-9141-12429b4fcdaf.mp4

**Comment by madsroskar** [comment] 2023-01-10 12:22
@dheeraj-m-kipl I haven't been able to reproduce this on my Samsung S20 FE.

Could you help me with the following additional information:

1. Could you see which version of `@react-native-camera-roll/camera-roll` you have installed in your `yarn.lock`?
2. Could you run `adb logcat -s "*:e"` while reproducing the issue, and give me the output generated while reproducing it?

**Comment by dheeraj-m-kipl** [comment] 2023-01-13 11:34
> @dheeraj-m-kipl I haven't been able to reproduce this on my Samsung S20 FE.
> 
> Could you help me with the following additional information:
> 
> 1. Could you see which version of `@react-native-camera-roll/camera-roll` you have installed in your `yarn.lock`?
> 2. Could you run `adb logcat -s "*:e"` while reproducing the issue, and give me the output generated while reproducing it?

@madsroskar 

1. `@react-native-camera-roll/camera-roll` - `v5.0.4`
2. Alright, I'll do that and post another comment with the info that comes out.

**Comment by vanGalilea** [comment] 2023-02-07 10:38
We're thinking internally on how to make this component more performant. Stay tuned!

**Comment by vanGalilea** [comment] 2023-03-08 11:14
> 2. Alright, I'll do that and post another comment with the info that comes out.

Hey @dheeraj-m-kipl any adb logcat logs from your side?

**Comment by dheeraj-m-kipl** [comment] 2023-03-13 08:10
> > 2. Alright, I'll do that and post another comment with the info that comes out.
> 
> Hey @dheeraj-m-kipl any adb logcat logs from your side?

@vanGalilea 
There are a lot of logcat logs. Which one would you want to see specifically?

**Comment by vishalnarkhede** [comment] 2023-09-22 11:06
@dheeraj-m-kipl sorry for the delays. There have been some changes to the team so this issue fell through the crack somehow. Are you facing this issue?

**Comment by dheeraj-m-kipl** [comment] 2023-09-22 12:03
> @dheeraj-m-kipl sorry for the delays. There have been some changes to the team so this issue fell through the crack somehow. Are you facing this issue?

Hi @vishalnarkhede 
Thanks for your response. I will try again with latest version to see if this issue is resolved.

**Comment by santhoshvai** [comment] 2023-11-14 14:11
Closing this issue since its not reproducible anymore. Feel free to reopen if still relevant.

**Closed by santhoshvai** 2023-11-14 14:11 UTC
Labels: Bug, Needs More Information, Needs Triaging, Performance
