### ISSUE TITLE
Message Input bug

### ISSUE THREAD

**Issue by hongsa** [GetStream/stream-chat-react-native#50] opened 2019-08-15 16:54 UTC
When I open channel.
In no message, Message input box is dissappear!

react-native:0.59.10
stream-chat-react-native": "0.1.17" || 0.1.18

<img width="310" alt="스크린샷 2019-08-15 오후 11 53 23" src="https://user-images.githubusercontent.com/8157631/63111518-0e851080-bfb8-11e9-9903-aa9a7aefb3b0.png">

**Comment by EJohnF** [comment] 2019-08-28 07:42
We have around the same issue. But I can see like 10 pixels messageInput at the bottom

I'd suggest checking on Android - in our case MessageInput is there

From code perspective what I can see that the problem is how the height of a component is calculated. You made it calculate and perform the animation on the keyboard opens. 
But it leads 1) to issues like this
2) not perfect UX - if you compare to WhatsApp, the screen goes up along with keyboard, not after.  In can be achieved by letting native side re-calculate screen sizes etc. But it's a different topic

**Comment by vishalnarkhede** [comment] 2019-09-26 15:13
@EJohnF @hongsa  I am not able to replicate the issue unfortunately. Can you tell me the version of emulator/device that you are using?

**Comment by tbarbugli** [comment] 2019-10-07 08:42
@EJohnF @hongsa ping

**Comment by EJohnF** [comment] 2019-10-07 15:42
@tbarbugli sorry, I already hardly remember details of this issue, since we managed to fix it about a month ago...

**Comment by vishalnarkhede** [comment] 2019-10-14 09:15
Closing this issue now !!

**Closed by vishalnarkhede** 2019-10-14 09:15 UTC
Labels: bug
