### ISSUE TITLE
TypeScript: 'View' cannot be used as a JSX component. Its instance type 'View' is not a valid JSX element

### ISSUE THREAD

**Issue by quachdev** [GetStream/stream-chat-react-native#1445] opened 2022-06-06 18:01 UTC
Our project is using TypeScript.

Our linter is firing off in all our files with something along the lines of:

```
'View' cannot be used as a JSX component. Its instance type 'View' is not a valid JSX element. The types returned by 'render()' are incompatible between these types.
```

Adding `stream-chat-react-native` looks to include `simple-markdown` as a dependency as well which is overlapping with the default `@types/react-native/node_modules/@types/react/index` `ReactNode` type.

I assume simple-markdown is used for stream-chat to work but, we are seeing these warnings everywhere in our app for different react-native Views since adding this dependency.

Is there a way to remove this or ignore the `simple-markdown` `ReactNode` type? 

- Package version (stream-chat-react-native/stream-chat-expo): **4.6.1**
- react-native version: **0.67.2**

package.json
```
"dependencies": {
    "@ada-support/react-native-sdk": "^1.2.0",
    "@datadog/mobile-react-native": "^1.0.0-rc4",
    "@datadog/mobile-react-navigation": "^1.0.0-rc4",
    "@react-native-async-storage/async-storage": "^1.15.17",
    "@react-native-clipboard/clipboard": "^1.8.5",
    "@react-native-community/cameraroll": "^4.1.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^9.0.0",
    "@react-native-picker/picker": "^2.2.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "@stream-io/flat-list-mvcp": "^0.10.2",
    "date-fns": "^2.28.0",
    "expo": "^44.0.6",
    "expo-barcode-scanner": "~11.2.0",
    "expo-blur": "~11.0.0",
    "expo-haptics": "~11.1.0",
    "expo-linking": "~3.0.0",
    "expo-local-authentication": "~12.1.0",
    "expo-localization": "~12.0.0",
    "expo-secure-store": "~11.1.0",
    "expo-sharing": "~10.1.0",
    "expo-store-review": "~5.1.0",
    "i18next": "^21.6.10",
    "launchdarkly-react-native-client-sdk": "^6.1.3",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "^5.0.1",
    "mixpanel-react-native": "^1.3.10",
    "react": "17.0.2",
    "react-i18next": "^11.15.3",
    "react-native": "0.67.2",
    "react-native-config": "^1.4.5",
    "react-native-date-picker": "^4.0.0",
    "react-native-device-info": "^8.4.8",
    "react-native-document-picker": "^8.1.0",
    "react-native-draggable-flatlist": "^3.1.0",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-haptic-feedback": "^1.13.1",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-image-resizer": "^1.4.5",
    "react-native-modal": "^13.0.0",
    "react-native-onesignal": "^4.3.9",
    "react-native-pager-view": "^5.4.4",
    "react-native-permissions": "^3.2.0",
    "react-native-persona": "1.3.1",
    "react-native-plaid-link-sdk": "^7.2.1",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.11.0",
    "react-native-share": "^7.6.0",
    "react-native-svg": "^12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-wagmi-charts": "^2.1.0",
    "react-native-webview": "^11.17.1",
    "react-query": "^3.34.0",
    "sift-react-native": "^0.1.3",
    "socket.io-client": "^4.4.1",
    "stream-chat-react-native": "^4.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/plugin-transform-react-jsx": "^7.14.9",
    "@babel/preset-typescript": "7.16.5",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^27.0.1",
    "@types/react": "^17.0.21",
    "@types/react-native": "^0.67.2",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^4.31.1",
    "@typescript-eslint/parser": "^4.31.1",
    "babel-jest": "^26.6.3",
    "eslint": "^7.25.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.3"
  },
```

Few screenshots for reference:

![Screen Shot 2022-06-06 at 1 33 44 PM](https://user-images.githubusercontent.com/11295669/172217111-4427ecf6-9f89-4f31-9c2d-deeb1f4a7e1b.png)
![Screen Shot 2022-06-06 at 1 44 07 PM](https://user-images.githubusercontent.com/11295669/172218072-686f187a-65d0-4940-b9b2-5c9529efd4dd.png)
![Screen Shot 2022-06-06 at 1 58 36 PM](https://user-images.githubusercontent.com/11295669/172218502-f844b561-1c56-4e32-903c-7533631450dd.png)

**Comment by khushal87** [comment] 2022-06-07 07:22
Hey @quachdev,

Can you share your package.json and the raw log, instead of a screenshot so that it will be helpful to judge the scenario? Besides, is there anything you might help us to reproduce this error?

Thanks.

**Comment by quachdev** [comment] 2022-06-07 07:48
Hey @khushal87, I've updated the original post with the package.json.

The screenshots are from VSCode and the linter for those types which logs:

```
'View' cannot be used as a JSX component. Its instance type 'View' is not a valid JSX element. The types returned by 'render()' are incompatible between these types.
```

I'm not sure how to reproduce this error other than bringing in `stream-chat-react-native` with a fresh project configured with TypeScript.

**Comment by khushal87** [comment] 2022-06-08 08:16
Hi @quachdev,

Thanks for reaching out.
To help you pinpoint this issue as fast as possible, we would like you to share a minimalistic repo where the problem is reproduced.

The fastest way to achieve that is with the following command to create a new RN project with Stream chat in it:
```
npx react-native init MyApp --template stream-chat-react-native-template
```

Please then share a Github repo with us, where we can explore the issue ourselves.

**Comment by quachdev** [comment] 2022-06-08 17:39
@khushal87 

Dug a bit further and found the underlying issue.

simple-markdown was one of the dependencies required to be installed and as a result it contains another `@types/react` as a dependency which happens to be version `18.0.12`. 

```
"@types/react@>=16.0.0":
  version "18.0.12" // CULPRIT HERE
  resolved "https://registry.yarnpkg.com/@types/react/-/react-18.0.12.tgz#cdaa209d0a542b3fcf69cf31a03976ec4cdd8840"
  integrity sha512-duF1OTASSBQtcigUvhuiTB1Ya3OvSy+xORCiEf20H0P0lzx+/KeVsA99U5UjLXSbyo1DRJDlLKqTeM1ngosqtg==
  dependencies:
    "@types/prop-types" "*"
    "@types/scheduler" "*"
    csstype "^3.0.2"
```

This overlapped with our existing version (`17.0.21`)

To resolve this we added `resolutions` to select the version in our `package.json`.

```
  "resolutions": {
    "@types/react": "17.0.21"
  }
```

No more linting errors!

**Comment by khushal87** [comment] 2022-06-13 05:07
I see that the version of `@types/react` in simple-markdown is as follows:
```
simple-markdown@^0.7.1:
  version "0.7.3"
  resolved "https://registry.yarnpkg.com/simple-markdown/-/simple-markdown-0.7.3.tgz#e32150b2ec6f8287197d09869fd928747a9c5640"
  integrity sha512-uGXIc13NGpqfPeFJIt/7SHHxd6HekEJYtsdoCM06mEBPL9fQH/pSD7LRM6PZ7CKchpSvxKL4tvwMamqAaNDAyg==
  dependencies:
    "@types/react" ">=16.0.0"
```

**Comment by vanGalilea** [comment] 2022-08-01 10:16
@quachdev  thanks for reaching out. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.

**Closed by vanGalilea** 2022-08-01 10:16 UTC
Labels: Needs Triaging
