### ISSUE TITLE
ChannelList component not working on expo

### ISSUE THREAD

**Issue by looju** [GetStream/stream-chat-react-native#1838] opened 2022-11-30 17:12 UTC
**Describe the bug**
ChannleList component returns an error on expo (abi 47_0_0.com.facebook.react.bridge.readableNativeArray cannot be cast to abi 47_0_0.com.facebook.react.bridge.readableMap). Thus, i'm unable to render the channel list 

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-expo): ^5.5.1
- expo version:~47.0.8
- react-native version: 0.70.5
- Device/Emulator (android) and OS version: Pixel API 31

**To Reproduce**

1- Device/Emulator (android) and OS version: Pixel API 31
. Go to 'https://github.com/looju/ChatTime'
2. Clone the repo
3. Run npx expo install to install dependencies
4. Run npx expo start
5. Press a or i to open on android or ios respectively
6. Within the app press the login button (i have disabled login functionality for now)
7. You should see the error now

**Expected behavior**
Expected to see a list of channels available to a user

**Screenshots**
![Screenshot (103)](https://user-images.githubusercontent.com/106563780/204862924-3a212021-2316-4c6f-87f5-2a4b523f72ed.png)

**Comment by vishalnarkhede** [comment] 2022-11-30 17:53
Thanks for detailed step of reproduction. Seems to be working fine on my end. Maybe something is missing between your actual project vs this repo? the only change I had to do was to add `flex: 1` to `GestureHandlerRootView`


![simulator_screenshot_7DC810B1-BEE8-42E2-A4F3-604CBFFFD280](https://user-images.githubusercontent.com/11586388/204870574-3e41705c-b4dc-4b40-a733-ef26bfa53958.png)

**Comment by looju** [comment] 2022-12-01 19:21
Did you open it on android? I have been trying it and i still get the same result. And this time, i even cloned the same repo just to be sure

**Comment by looju** [comment] 2022-12-02 07:53
Please I really need help on this... Just tried it yet again and still the same error

**Comment by looju** [comment] 2022-12-02 09:34
Thank you so much for trying it out. Please any idea as to how to fix this? Thank you so much @vishalnarkhede

**Comment by looju** [comment] 2022-12-03 14:14
Hello please i am still waiting for a response...

**Comment by vishalnarkhede** [comment] 2022-12-03 20:16
Hey @looju it actually worked for me on second run on android. So we are not able to reproduce this issue at this point.

We will try to do more investigation next week and get back to you

**Comment by looju** [comment] 2022-12-04 23:22
Ok... Could you give since home as to the difference in the two runs? Was there something you had to do to make it with the second time?

**Comment by vishalnarkhede** [comment] 2022-12-05 13:39
Nothing really. I think Expo Go app version of android simulator was outdated. So I had to uninstall Expo Go app from simulator ... and let expo cli install the required version.

**Comment by khushal87** [comment] 2022-12-06 11:14
Hi @looju,

When I see your implementation and dependencies in https://github.com/looju/ChatTime/blob/main/package.json, it doesn't look friendly, and creating an app using our tutorial doesn't cause any such issues on our side that we can reproduce it. I would suggest you follow the following:
 - Try creating an application from scratch using our [Tutorial](https://getstream.io/chat/react-native-chat/tutorial/?language=expo) and see if you still face the issue in that application.
 - If this doesn't work, please share with us the bare minimum repo where you can reproduce this issue with the packages as needed for stream chat to run.

Also, please try downgrading your expo version to 46 since we do not recommend/support 47 in our SDK currently. I am closing this issue until then. Please feel free to reach us or open this issue again if you face the issue in the new setup.

**Closed by khushal87** 2022-12-06 11:14 UTC
Labels: Needs More Information, Needs Triaging
