### ISSUE TITLE
Investigate crashes related to bottom sheet in chat

### ISSUE THREAD

**Issue by diego-paired** [GetStream/stream-chat-react-native#1264] opened 2022-04-06 09:08 UTC
Using React Native 67, stream chat 4.3.0.

We have been seeing lots of crashes coming from the BottomSheet library, which is only used by Stream in our project. The errors only seem to happen on Android and look like this:

![image](https://user-images.githubusercontent.com/55058765/161939189-ebc30e14-4266-45a4-8955-aaf9b452f23f.png)

```

Snap point '-106.28571464901881' is invalid. if you want to allow user to close the sheet, Please use 'enablePanDownToClose' prop.

This error is located at:
    in BottomSheet
    in Unknown
    in ThemeProvider
    in ImageGalleryProvider
    in AttachmentPickerProvider
    in MessageOverlayProvider
    in TranslationProvider
    in OverlayProvider
    in ChatOverlay
    in PartnerChat

```

The snap point value changes (there are a few different values, probably for different screen aspect ratios) but it's always negative.

I haven't been able to reproduce the issue myself unfortunately.

gz#21509

**Comment by madsroskar** [comment] 2022-04-06 09:29
Thanks for reporting this, @diego-paired. I'm trying to reproduce this issue at the moment. Could you check your `yarn.lock` or `package-lock.json` and check which version of `@gorhom/bottom-sheet` that is installed?

**Comment by diego-paired** [comment] 2022-04-06 10:09
@madsroskar 

```
"@gorhom/bottom-sheet@4.1.5":
  version "4.1.5"
  resolved "https://registry.yarnpkg.com/@gorhom/bottom-sheet/-/bottom-sheet-4.1.5.tgz#35341d45799de28082c380db6639537b04fa0b26"
  integrity sha512-3F5P8jK3NXwT2lGwkAdkdLwDVHaRvMZalUTXjK6Ogf0Tki6idffJ3TNlQZlg8k6+OnXAx0+i80f4XaI+J4GFrA==
  dependencies:
    "@gorhom/portal" "^1.0.11"
    invariant "^2.2.4"
    nanoid "^3.1.20"
    react-native-redash "^16.1.1"

"@gorhom/portal@^1.0.11":
  version "1.0.12"
  resolved "https://registry.yarnpkg.com/@gorhom/portal/-/portal-1.0.12.tgz#1c0deabb3f9057c736352a88bae9ca891a100346"
  integrity sha512-JOYe85RUwiksgdMbhLWDCLpH3kgFFz+LCu1lnxOMMBQSfAKtL5kkTKVrhtmQ3Lq3lJM2paGnLc4wJrlVuaC5Jw==
  dependencies:
    nanoid "^3.1.23"
```

**Comment by vishalnarkhede** [comment] 2022-04-07 08:01
@diego-paired do you have device info as well, on which users were facing this issue? That would be helpful for us to reproduce it on our end. We are having a little hard time reproducing it on our side

**Comment by diego-paired** [comment] 2022-04-07 09:17
These are the top devices affected, doesn't seem to be device related:
![image](https://user-images.githubusercontent.com/55058765/162164705-aed59f3d-2973-45e8-aa55-4cef4779371d.png)

I have seen Android 9, 10 and 12 so that might not help narrow down either.

We are using react-native-screens with native screens in the app, the chat screen is inside a stack and the root component is the `OverlayProvider`.

The main activity is set up as such:
```
        <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|screenSize|orientation|uiMode"
            android:exported="true"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustResize" />
```

**Comment by diego-paired** [comment] 2022-04-12 13:53
```    const snapPoints = useMemo(
      () => [
        attachmentPickerBottomSheetHeight ??
          308 + (fullScreenHeight - screenHeight + androidBottomBarHeightAdjustment) - handleHeight,
        fullScreenHeight - topInset - handleHeight,
      ],
      [
        androidBottomBarHeightAdjustment,
        attachmentPickerBottomSheetHeight,
        fullScreenHeight,
        handleHeight,
        screenHeight,
        topInset,
      ],
    );```
Couldn't it be that one of these calculations returns a negative value? perhaps better to safeguard against that?

**Comment by vishalnarkhede** [comment] 2022-04-12 14:56
Hey @diego-paired yeah if you set negative value it does result into crash. We are just trying to figure out what devices will this value result into a negative

**Comment by zT0Tz** [comment] 2022-05-19 16:42
We are also getting the same crash since upgrading to v4(now with 4.3.1), only on android devices

**Comment by diego-paired** [comment] 2022-05-19 17:11
we are using react-native-screens with react-navigation, we have noticed on other bugs that on some android devices the device height might be zero under some unknown circumstances

**Comment by vanGalilea** [comment] 2022-05-20 17:40
@diego-paired Thanks for reaching out, will investigate this and loop back to you 👍🏻

**Comment by jamiekieranmartin** [comment] 2022-06-13 05:30
Any update on this? This is currently the highest unsolved crash cause for us on Android 😕 

Similar setup to @diego-paired 

react-native-screens, react-navgiation, etc

- `react-native 0.66.1`
- `stream-chat-react-native ^4.3.1`

```xml
 <activity android:name=".MainActivity" android:label="@string/app_name"
              android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
              android:launchMode="singleTask" android:windowSoftInputMode="adjustResize"
              android:screenOrientation="portrait">
```

**Comment by diego-paired** [comment] 2022-06-14 07:12
@jamiekieranmartin the issue seems to have been fixed as of `stream-chat-react-native@4.7.0`

**Comment by santhoshvai** [comment] 2022-07-05 07:30
Thanks, @diego-paired for the update. I am closing this issue. 

@jamiekieranmartin  feel free to reopen this if you see it again.

**Closed by santhoshvai** 2022-07-05 07:30 UTC
Labels: Needs Triaging

**Comment by tao-qian** [comment] 2023-12-08 02:37
Hi! We started seeing this issue recently on the latest version of the SDK. Are there any context on what was done to fix the issue at the time?
