### ISSUE TITLE
[🐛] Reaction icon is missed for giphy message when the user leaves chat and back

### ISSUE THREAD

**Issue by habrahamyanmabbly** [GetStream/stream-chat-react-native#2233] opened 2023-09-15 14:07 UTC
## Issue

The issue is applicable also for own and another user's Giphy messages

* Create Giphy message
* Long tap on the Giphy message
* Tap on any reaction on the reactions bar pop-up
* Leave chat
* Go back to the chat

**Expected behavior**
* Reaction icon is missed for giphy message on the chat screen

## Project Related Information

<details>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

<details>
<p>

#### `package.json`:

```json
{
	"name": "t21-connect",
	"description": "This is frontend app for a exclusive peer membership organization of high-net-worth entrepreneurs, investors, and executives.",
	"version": "2.1.2",
	"main": "index.js",
	"private": true,

	"scripts": {
		"start": "npx expo start",
		"add:component": "hygen add component",
		"add:module-component": "hygen add module-component",
		"add:screen": "hygen add screen",
		"add:query-hook": "hygen add query-hook",
		"add:mutation-hook": "hygen add mutation-hook",
		"i18n:scan": "i18next-scanner",
		"lint": "yarn run eslint --fix && yarn tsc --noEmit",
		"clear-cache": "watchman watch-del-all && rimraf $TMPDIR/react-* && yarn cache clean --force && rimraf $TMPDIR/react-native-packager-cache-* && rimraf $TMPDIR/metro-bundler-cache-* && rimraf $TMPDIR/metro*",
		"test": "jest",
		"test:watch": "jest --watch",
		"dev": "expo start --dev-client",
		"android": "npx expo start --android",
		"android:build": "npx eas build --local --platform android --profile dev",
		"android:logcat": "adb logcat *:S ReactNative:V ReactNativeJS:V",
		"build-submit:dev-internal": "APP_ENV=dev eas build --profile dev-internal --non-interactive --no-wait --platform all",
		"build-submit:dev-appstore": "APP_ENV=dev eas build --profile dev-appstore --non-interactive --no-wait --platform all --auto-submit-with-profile=dev",
		"build-submit:qa1-internal": "APP_ENV=qa1 eas build --profile qa1-internal --non-interactive --no-wait --platform all",
		"build-submit:qa2-internal": "APP_ENV=qa2 eas build --profile qa2-internal --non-interactive --no-wait --platform all",
		"build-submit:qa1-appstore": "APP_ENV=qa1 eas build --profile qa1-appstore --non-interactive --no-wait --platform all --auto-submit-with-profile=qa1",
		"build-submit:qa2-appstore": "APP_ENV=qa2 eas build --profile qa2-appstore --non-interactive --no-wait --platform all --auto-submit-with-profile=qa2",
		"build-submit:staging": "APP_ENV=staging eas build --profile staging --non-interactive --no-wait --platform all --auto-submit-with-profile=staging",
		"build-submit:staging:all": "APP_ENV=staging eas build --profile staging --non-interactive --no-wait --platform all --auto-submit-with-profile=staging",
		"build-submit:staging:ios": "APP_ENV=staging eas build --profile staging --non-interactive --no-wait --platform ios --auto-submit-with-profile=staging",
		"build-submit:staging:android": "APP_ENV=staging eas build --profile staging --non-interactive --no-wait --platform android --auto-submit-with-profile=staging",
		"build-submit:production": "APP_ENV=production eas build --profile production --non-interactive --no-wait --platform all --auto-submit-with-profile=production",
		"ios": "npx expo start --ios",
		"ios:build": "npx eas build --local --platform ios --profile dev",
		"flipper": "METRO_SERVER_PORT=19000 open -a Flipper.app",
		"prepare": "husky install configs/husky",
		"postinstall": "patch-package",
		"ci:lint": "lockfile-lint --path yarn.lock --type yarn --allowed-hosts npm github.com codeload.github.com registry.yarnpkg.com npm.pkg.github.com && eslint src --quiet && tsc --noEmit",
		"ci:test": "CI=true jest --ci --runInBand --watchAll=false --coverage",
		"commit:pre": "lint-staged",
		"commit:msg": "commitlint --edit $1"
	},
	"dependencies": {
		"@algolia/cache-common": "^4.14.3",
		"@bothrs/expo-mixpanel-analytics": "^2.0.0",
		"@config-plugins/react-native-blob-util": "^6.0.0",
		"@config-plugins/react-native-pdf": "^6.0.0",
		"@expo-google-fonts/karla": "^0.2.2",
		"@expo/config-plugins": "~7.2.2",
		"@formatjs/intl-datetimeformat": "^6.0.3",
		"@formatjs/intl-displaynames": "^6.1.2",
		"@formatjs/intl-getcanonicallocales": "^2.0.2",
		"@formatjs/intl-listformat": "^7.1.2",
		"@formatjs/intl-locale": "^3.0.3",
		"@formatjs/intl-numberformat": "^8.0.3",
		"@formatjs/intl-pluralrules": "^5.0.3",
		"@formatjs/intl-relativetimeformat": "^11.0.3",
		"@gorhom/portal": "^1.0.14",
		"@hamidfzm/react-native-image-viewing": "^1.0.0",
		"@nghinv/react-native-alphabet-list": "^0.0.4",
		"@plussub/srt-vtt-parser": "^1.1.0",
		"@react-native-anywhere/polyfill-base64": "^0.0.1-alpha.0",
		"@react-native-async-storage/async-storage": "^1.19.3",
		"@react-native-community/datetimepicker": "7.2.0",
		"@react-native-community/hooks": "^2.8.1",
		"@react-native-community/netinfo": "9.3.10",
		"@react-navigation/bottom-tabs": "^6.5.7",
		"@react-navigation/devtools": "^6.0.18",
		"@react-navigation/drawer": "^6.6.2",
		"@react-navigation/elements": "^1.3.17",
		"@react-navigation/material-top-tabs": "^6.6.2",
		"@react-navigation/native": "^6.1.6",
		"@react-navigation/native-stack": "^6.9.12",
		"@react-navigation/stack": "^6.3.16",
		"@reduxjs/toolkit": "^1.8.0",
		"@sentry/react-native": "5.5.0",
		"@shopify/flash-list": "^1.5.0",
		"@tanstack/react-query": "^4.33.0",
		"algoliasearch": "^4.13.1",
		"async-await-mutex-lock": "^1.0.10",
		"axios": "^0.27.2",
		"bottlejs": "^2.0.0",
		"crypto-es": "^1.2.7",
		"currency-codes": "^2.1.0",
		"currency-symbol-map": "^5.1.0",
		"dayjs": "^1.11.9",
		"deprecated-react-native-prop-types": "^2.3.0",
		"dotenv": "^16.0.0",
		"expo": "^49.0.8",
		"expo-activity-feed": "1.1.0",
		"expo-application": "~5.3.0",
		"expo-av": "~13.4.1",
		"expo-barcode-scanner": "~12.5.3",
		"expo-blur": "~12.4.1",
		"expo-build-properties": "~0.8.3",
		"expo-calendar": "~11.3.0",
		"expo-camera": "~13.4.2",
		"expo-clipboard": "~4.3.1",
		"expo-constants": "~14.4.2",
		"expo-device": "^5.4.0",
		"expo-document-picker": "~11.5.4",
		"expo-file-system": "~15.4.3",
		"expo-font": "~11.4.0",
		"expo-haptics": "~12.4.0",
		"expo-image": "~1.3.2",
		"expo-image-manipulator": "~11.3.0",
		"expo-image-picker": "~14.3.2",
		"expo-intent-launcher": "~10.7.0",
		"expo-linear-gradient": "~12.3.0",
		"expo-linking": "~5.0.2",
		"expo-local-authentication": "~13.4.1",
		"expo-localization": "~14.3.0",
		"expo-media-library": "~15.4.1",
		"expo-navigation-bar": "~2.3.0",
		"expo-notifications": "~0.20.1",
		"expo-permissions": "~14.2.1",
		"expo-screen-capture": "~5.3.0",
		"expo-screen-orientation": "~6.0.5",
		"expo-secure-store": "~12.3.1",
		"expo-sharing": "~11.5.0",
		"expo-status-bar": "~1.6.0",
		"expo-task-manager": "~11.3.0",
		"expo-video-thumbnails": "~7.4.0",
		"formik": "^2.4.3",
		"getstream": "^8.1.0",
		"i18n-iso-countries": "^7.6.0",
		"i18n-possessive": "^1.0.0",
		"i18next": "^21.6.11",
		"jest-environment-jsdom": "^29.4.3",
		"jwt-decode": "^3.1.2",
		"lodash": "^4.17.21",
		"markdown-to-txt": "^2.0.1",
		"mime-types": "^2.1.35",
		"mitt": "^3.0.0",
		"p-retry": "^5.1.2",
		"p-timeout": "^6.1.1",
		"patch-package": "^6.4.7",
		"react": "18.2.0",
		"react-countdown-hook": "^1.1.1",
		"react-devtools-core": "^4.26.0",
		"react-dom": "18.2.0",
		"react-error-boundary": "^3.1.4",
		"react-fast-compare": "^3.2.0",
		"react-i18next": "^11.15.5",
		"react-native": "0.72.4",
		"react-native-animatable": "^1.3.3",
		"react-native-blob-util": "^0.19.0",
		"react-native-calendars": "1.1284.0",
		"react-native-collapsible": "1.6.0",
		"react-native-draglist": "^3.5.1",
		"react-native-elements": "3.4.2",
		"react-native-gesture-handler": "~2.12.0",
		"react-native-hide-with-keyboard": "^1.2.1",
		"react-native-iphone-x-helper": "1.3.1",
		"react-native-keyboard-aware-scroll-view": "^0.9.5",
		"react-native-logs": "^5.0.1",
		"react-native-modal-datetime-picker": "^14.0.0",
		"react-native-modalfy": "^3.1.1",
		"react-native-offline": "^6.0.0",
		"react-native-open-maps": "^0.4.0",
		"react-native-pager-view": "6.2.0",
		"react-native-parsed-text": "^0.0.22",
		"react-native-pdf": "^6.7.1",
		"react-native-popup-menu": "^0.16.1",
		"react-native-portalize": "^1.0.7",
		"react-native-qrcode-svg": "6.1.2",
		"react-native-quick-base64": "^2.0.5",
		"react-native-reanimated": "~3.3.0",
		"react-native-redash": "^16.2.3",
		"react-native-render-html": "^6.3.4",
		"react-native-safe-area-context": "4.6.3",
		"react-native-screens": "~3.22.0",
		"react-native-shadow-2": "^7.0.8",
		"react-native-svg": "13.9.0",
		"react-native-svg-transformer": "^1.0.0",
		"react-native-tab-view": "3.1.1",
		"react-native-toast-message": "2.1.5",
		"react-native-url-polyfill": "^1.3.0",
		"react-native-uuid": "^2.0.1",
		"react-native-vector-icons": "^9.0.0",
		"react-native-viewport-helpers": "^1.0.0",
		"react-native-webview": "13.2.2",
		"react-redux": "^7.2.6",
		"react-use": "^17.4.0",
		"react-use-event-hook": "^0.9.6",
		"redux-persist": "^6.0.0",
		"reinspect": "^1.1.0",
		"semver": "^7.3.8",
		"sentry-expo": "~7.0.0",
		"showdown": "^2.1.0",
		"stream-chat-expo": "^5.13.0",
		"timezone-abbreviations": "^1.2.6",
		"toggle-switch-react-native": "^3.3.0",
		"use-debounce": "^7.0.1",
		"use-sync-external-store": "^1.2.0",
		"yup": "^0.32.11"
	},
	"devDependencies": {
		"@babel/core": "^7.18.6",
		"@commitlint/cli": "^16.1.0",
		"@expo/ngrok": "2.4.3",
		"@jest-performance-reporter/core": "2.1.2",
		"@jest/types": "^27.5.0",
		"@react-native-community/eslint-config": "^3.0.1",
		"@sentry/types": "^7.9.0",
		"@testing-library/jest-native": "^4.0.4",
		"@testing-library/react-hooks": "^7.0.2",
		"@testing-library/react-native": "^9.0.0",
		"@types/axios": "^0.14.0",
		"@types/jest": "^27.4.0",
		"@types/lodash": "^4.14.178",
		"@types/mime-types": "^2.1.1",
		"@types/p-timeout": "^1.2.2",
		"@types/react": "~18.2.14",
		"@types/showdown": "^2.0.0",
		"@types/use-sync-external-store": "^0.0.3",
		"@typescript-eslint/eslint-plugin": "^5.10.2",
		"@typescript-eslint/parser": "^5.10.2",
		"alias-hq": "^5.3.2",
		"babel-plugin-module-resolver": "^5.0.0",
		"commitlint-config-jira": "^1.5.2",
		"commitlint-plugin-jira-rules": "^1.5.1",
		"conventional-changelog-cli": "^2.2.2",
		"esbuild": "^0.14.39",
		"esbuild-jest": "^0.5.0",
		"eslint": "8.22.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-import-resolver-babel-module": "^5.3.1",
		"eslint-plugin-boundaries": "^2.9.0",
		"eslint-plugin-clean-regex": "^0.5.2",
		"eslint-plugin-jest": "^26.1.0",
		"eslint-plugin-json": "^3.1.0",
		"eslint-plugin-module-resolver": "^1.4.0",
		"eslint-plugin-no-async-foreach": "^0.1.1",
		"eslint-plugin-no-await-in-promise": "^1.1.1",
		"eslint-plugin-prettier": "^4.0.0",
		"eslint-plugin-react": "^7.30.0",
		"eslint-plugin-react-i18n": "^1.0.3",
		"eslint-plugin-react-native": "hsource/eslint-plugin-react-native#v4.0.0-wanderlog.2",
		"eslint-plugin-react-native-globals": "^0.1.2",
		"eslint-plugin-sonarjs": "^0.11.0",
		"eslint-plugin-testing-library": "^5.5.1",
		"eslint-plugin-usememo-recommendations": "^1.0.2",
		"husky": "^7.0.4",
		"hygen": "^6.1.0",
		"i18next-scanner": "^3.1.0",
		"jest": "^29.2.1",
		"jest-expo": "^48.0.1",
		"jest-extended": "^2.0.0",
		"jest-github-actions-reporter": "^1.0.3",
		"jest-mock-extended": "^2.0.4",
		"jest-transform-stub": "^2.0.0",
		"jest-transformer-svg": "^2.0.0",
		"lint-staged": "^12.3.3",
		"lockfile-lint": "^4.6.2",
		"mockdate": "^3.0.5",
		"prettier": "^2.5.1",
		"react-native-svg-transformer": "^1.0.0",
		"rimraf": "^3.0.2",
		"typescript": "5.1.3"
	},
	"resolutions": {
		"@types/react": "~18.0.0",
		"axios": "^0.27.2",
		"@expo/config-plugins": "~7.2.2",
		"dayjs": "^1.11.9",
		"expo-device": "^5.4.0",
		"@react-native-async-storage/async-storage": "1.19.3"
	}
}

```
used this instead 
**`
npx expo-env-info
` output:**

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/mabbly/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 3.4.1
    Expo Workflow: managed

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`

"stream-chat-expo": "^5.13.0",
"getstream": "^8.1.0",
` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

[How To Reproduce Video](https://gemoo.com/tools/upload-video/share/561300080789409792?codeId=Ml3r7gb406aXb&card=561300076632854528&origin=videolinkgenerator)

---

**Comment by juliayojji** [comment] 2023-09-29 09:53
Same issue. 
Any updates here?

**Comment by vishalnarkhede** [comment] 2023-09-29 14:54
Hey @juliayojji @habrahamyanmabbly  we will take a look and get back to you. It may take upto mid-next week :)

**Comment by habrahamyanmabbly** [comment] 2023-10-02 09:25
@vishalnarkhede please keep us updated. Thanks !

**Comment by habrahamyanmabbly** [comment] 2023-10-10 13:09
@vishalnarkhede hey, if there are any updates please let me know.

**Comment by khushal87** [comment] 2023-10-19 05:15
Hey @habrahamyanmabbly, I just tried reproducing the same on our side but couldn't do so. Do you have any additional customization that causes this bug on your end?

**Comment by Paiman-Rasoli** [comment] 2023-10-20 16:02
@khushal87 Hi, I can check this bug, feel free to assign it to me.

**Comment by khushal87** [comment] 2023-11-02 06:44
Closing this issue because of no response and inability to reproduce it. Please feel free to open it if it is still existent. Thanks 😄

**Closed by khushal87** 2023-11-02 06:44 UTC
Labels: Needs Triaging
