### ISSUE TITLE
ChannelList Component Pagination does not work as expected 

### ISSUE THREAD

**Issue by hashrc** [GetStream/stream-chat-react-native#1649] opened 2022-08-13 04:19 UTC
**Describe the bug**
In ChannelList Component Total number of channels returned is different for different limit values set in options object.

**Dev environment info (please complete/provide the following information):**

- Package versions
 "stream-chat": "^6.7.3",
 "stream-chat-expo": "^4.11.0",

- react-native or expo version
   "expo": "^45.0.5",
   "react-native": "0.68.2",

- Device/Emulator (android/ios) and OS version
   Android
   
   
**To Reproduce**
```
const filters = {
    members: { $in: ['production-test-user-418-ef2bbc9f-2186-424a-9c66-54b482931ecf'] },
    type: 'messaging',
  }
  const sort = { last_message_at: -1 }
  const options = {
    limit : 10,
    state: true,
    watch: true,
  }

<ChannelList
    filters={filters}
    options={options}
    sort={sort}    
/>
```

Use these values.  Total channels listed is not cosistent for different values for limit.
e.g. if limit is kept 30, total channels returned are 23 and listed.  if limit is kept as 10, total channels returned in second page are 9 and pagination sotps. so only 19 channels are listed.

**Expected behavior**
Total number of channels returen after pagination should be same regarless of limit value

**Additional context**
Problem might be for some users only.

**Comment by vanGalilea** [comment] 2022-08-30 14:42
@hashrc thanks for reaching out. We have seen this issue previously, and the root cause in most of the cases was the sort. If the `last_messages_at` field on the channel is null (basically an empty channel), then our backend won't be able to sort those channels appropriately. 

So you should EITHER replace `last_message_at` sort param with `{ last_updated: -1 }`, which is also a default sort for channels API. So for this case, you simply remove the sort prop from the `ChannelList` component OR add a secondary sort parameter to sort null values of `last_message_at` field, as shown in the following code snippet:

```
sort={[
 { last_message_at: -1 },
 { cid: -1 }
]}
```
Please let me know if this helps and works!

**Comment by vanGalilea** [comment] 2022-09-13 08:43
@hashrc I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.

**Closed by vanGalilea** 2022-09-13 08:43 UTC
Labels: Needs Triaging
