### ISSUE TITLE
[🐛] [ios] 🔥 message cannot be send when using "sliding your finger to type" with a single word

### ISSUE THREAD

**Issue by RRaideRR** [GetStream/stream-chat-react-native#2132] opened 2023-06-02 09:07 UTC
## Issue

I cannot send a single word message on any iOS phone if I'm using my fingers to slide on the keyboard (see also attached video in Screenshots section). 

---

### Steps to reproduce

1. Follow the steps to run the [_ExpoMessaging_ example app](https://github.com/GetStream/stream-chat-react-native/tree/develop/examples/ExpoMessaging)
2. Go into a channel 
3. Write a single word by sliding your finger on the keyboard
4. Send the message
5. Repeat step 3 and you'll see that you cannot send the message

---

### Expected behavior

I expect that the single word can be send without typing another word or whitespace.

---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

---

### Offline support

- [X] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

```
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 741.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
    - [ X] iOS
    - [ ] Android
- **`stream-chat-expo`: 5.15.0
- Device/Emulator info:
  - happens on every iOS device and iOS simulator

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

https://github.com/GetStream/stream-chat-react-native/assets/3411292/1eeec0fe-6e95-4e19-8312-087b8cdddfb1

</p>
</details>

---

**Comment by khushal87** [comment] 2023-06-05 05:14
Hey @RRaideRR, I was trying to reproduce this issue on iPhone 13 real device, and it doesn't seem to happen. Can you check if it happens on a real device? Thanks 😄

**Comment by khushal87** [comment] 2023-06-05 06:12
Also, we are not able to reproduce it on iPhone SE(3rd generation) simulator.

https://github.com/GetStream/stream-chat-react-native/assets/39884168/1009b3ff-4bcf-455a-a37a-fe30a33da1a8

**Comment by RRaideRR** [comment] 2023-06-05 16:07
> Hey @RRaideRR, I was trying to reproduce this issue on iPhone 13 real device, and it doesn't seem to happen. Can you check if it happens on a real device? Thanks 😄

I've tested it on an iPhone 7 Plus (iOS 15.7.5), on an iPhone 7 (iOS 15.7.5) and an iPhone 14 (iOS 16.1.2) --> it occurs on all of these real devices. 

I'm trying to find the differences in our screencasts. Your project is not the ExpoMessaging example - right (it looks different to my video)? Could this be a difference? Expo <--> React Native?

**Comment by khushal87** [comment] 2023-06-05 17:24
No, I  have tested it on TypescriptMessaging and SampleApp. They both use React Native CLI and not expo.

**Comment by RRaideRR** [comment] 2023-06-06 05:53
> No, I have tested it on TypescriptMessaging and SampleApp. They both use React Native CLI and not expo. I hope you are also not using expo.

As stated in the bug ticket, I was using the _ExpoMessaging_ example app, so yes: I'm using expo there :-) (however not Expo Go).

**Comment by khushal87** [comment] 2023-06-06 06:11
You have mentioned `**stream-chat-react-native: 5.15.0` in the issue description. Why are you using `stream-chat-react-native` in an Expo environment?

**Comment by RRaideRR** [comment] 2023-06-06 06:31
> Hey, sorry but in you have mentioned `**stream-chat-react-native: 5.15.0` in the issue description. Why are you using `stream-chat-react-native` in an Expo environment?
> 
> In the issue description, I can't see any mention of expo cli, if I am not reading it wrong.

You're right @khushal87. I should have made that clearer. I thought that when using the ExpoMessaging example, its automatically using `stream-chat-expo`. I also made a mistake copying the package name with the version number - you're right there as well (I'm using stream-chat-expo not stream-chat-react-native). Sorry mate!

**Comment by khushal87** [comment] 2023-06-07 12:06
Hey, @RRaideRR, we were able to reproduce it on the expo environment. This seems to be a weird bug. Thanks for bringing this up. We will have a look at it and get back to you soon.

**Comment by khushal87** [comment] 2023-11-20 08:18
I am not able to reproduce it anymore on the latest version of our SDK and on RN version - 0.71.14 so it must be solved therefore closing it. Please reopen this issue if you still find it an issue. Thanks 😄

**Closed by khushal87** 2023-11-20 08:18 UTC
Labels: Bug, User Experience

**Comment by RRaideRR** [comment] 2023-11-20 10:32
Looks good :-).
