### ISSUE TITLE
Error: You can't use a channel after client.disconnect() was called

### ISSUE THREAD

**Issue by ZhengDao375** [GetStream/stream-chat-react-native#823] opened 2021-08-26 21:26 UTC
I just saw this Error:
"You can't use a channel after client.disconnect() was called.

**Expected behavior**
I want the original chat channel when the channel back from background to foreground.

![image_2021_08_26T21_23_46_775Z](https://user-images.githubusercontent.com/54350519/131038307-0b1ee924-f01b-47a7-8ba6-090a2c2ff9bc.png)

gz#14632

**Comment by streamiosupport** [comment] 2021-08-31 19:16
Agent comment from Zachery Converse in <a href='https://getstream.zendesk.com/agent/tickets/14632'>Zendesk ticket #14632</a>:<br><br>Hi,

Thanks for these details. In order to use a channel, the user must be connected.

Please ensure that client.connectUser() is called with the current user after client.disconnect()

Feel free to provide more context and specifics on expected behavior vs actual.

Cheers,
-Zachery
 Getstream.io
<br><p><em><small>°°°</small></em></p>

**Comment by vishalnarkhede** [comment] 2021-09-16 14:59
This looks like an integration issue, so going to close this one and continue the conversation over ZD ticket.

**Closed by vishalnarkhede** 2021-09-16 14:59 UTC
