### ISSUE TITLE
Push notifications v2 will never work reliably for iOS

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-react-native#1268] opened 2022-04-07 14:40 UTC
After much digging I've come to the conclusion that the current proposal for push notifications v2 will never work reliably for iOS.

`setBackgroundMessageHandler` is super unreliable for iOS. It is [only called when the payload is data-only](https://github.com/invertase/react-native-firebase/discussions/6182#discussioncomment-2510043). Data-only remote notifications are [considered very low priority by apple and the device will only accept two or three per hour](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc). They are subject to multiple extra throttling heuristics [e.g. low battery mode, device is overheating](https://github.com/invertase/react-native-firebase/issues/4705#issuecomment-846572270).

Also with v2 there is no way to get the unread badge count easily.

Therefore I would urge you to reconsider the new v2 approach. 

Have you tested v2 on iOS in production??

gz#21584

**Comment by santhoshvai** [comment] 2022-04-12 08:15
Hey, @dmitriiivashko @mfbx9da4. Many thanks for sharing your concern here. We would need to update our documentation regarding the ios/android platform limitations and the docs will be updated soon. 

I did setup a sample app to test it and got `setBackgroundMessageHandler` to work on a mixed payload (data + notification) when I enabled "background fetch" and "background processing". Additionally the payload must also have ` "content_available": true`. I should note that there is some throttling there. Suppose I increment the badge count by one on the background handler. The increment doesnt always happen on every push but is rather queued. Meaning that in the next push or the push after, the badge count increments by 2 or 3 respectively. 

It would be very helpful for us if you can test this at your end and get back to us regarding this. 

Our current push v2 template does not have ` "content_available": true` enabled, so we would have to add this. We are currently finalising template customisation and the docs should be available soon about this too.

**Comment by mfbx9da4** [comment] 2022-04-12 09:28
Yes I did. I also had enabled those capabilities. Were you running iOS 15?

**Comment by santhoshvai** [comment] 2022-04-12 10:20
Hi @mfbx9da4,  yes I am using iOS 15.

if apns payload is present, it will [override](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#apnsconfig) the notification, and you [should not be using camelCase](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943363) for `content-available`. And the structure misses "payload".

can you try the one below for your apns, this should work

```
"apns":{
   "payload":{
      "aps":{
         "alert":{
            "body":"Test body",
            "title":"Test title"
         },
         "custom-data":{
            // any custom fields
         },
         "content-available":true
      }
   }
```

The structure is [here](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#apnsconfig)

**Comment by dmitriiivashko** [comment] 2022-04-12 11:40
The problem is that getstream seems to send an `aps` payload with both `content-available` and `alert`

If both are specified, `setBackgroundMessageHandler` is never triggered on iOS and the content from `alert` is displayed by iOS. Yes, you can implement an iOS notification extension, but I'd prefer to deal with it with what rnfirebase has to offer.

Examples

This will wake up the app and will trigger `setBackgroundMessageHandler` as expected:

```js
  const firebaseMessage: admin.messaging.TokenMessage = {
    token: pushToken,
    data: {
      my_custom_parameter: 'wow2',
    },
    apns: {
      headers: {
        'apns-push-type': 'background',
        'apns-priority': '5',
        'apns-topic': 'com.myapp',
      },
      payload: {
        aps: {
          contentAvailable: true,
          priority: 'high',
        },
      }
    },
  };
  return admin.messaging().send(firebaseMessage);
```

however this will display a `hello world` notification and will not trigger the `setBackgroundMessageHandler`:

```js
  const firebaseMessage: admin.messaging.TokenMessage = {
    token: pushToken,
    data: {
      my_custom_parameter: 'wow2',
    },
    apns: {
      headers: {
        'apns-push-type': 'background',
        'apns-priority': '5',
        'apns-topic': 'com.teamgo.godisco',
      },
      payload: {
        aps: {
          alert: {
            body: 'Hello',
            title: 'World',
            subtitle: 'test',
          },
          contentAvailable: true,
          priority: 'high',
        },
      }
    },
  };
  return admin.messaging().send(firebaseMessage);
```

**Comment by santhoshvai** [comment] 2022-04-12 14:19
Hey, @dmitriiivashko I did try out the exact payload that you sent and the `setBackgroundMessageHandler` and it did work.

However, as per the [apple docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943363), alert should not be used along with `content-available`. So this really unreliable I think.

> The background notification flag. To perform a silent background update, specify the value 1 and don't include the alert, badge, or sound keys in your payload. See Pushing Background Updates to Your App.

So I think the best way forward is to implement a native iOS push notification extension for now. Stream's backend team is actively working on supporting the firebase template customization feature. It should be available very soon. This would enable adding [notifee_options payload](https://notifee.app/react-native/docs/ios/remote-notification-support).

I will soon be updating the docs with the platform limitations and many thanks for your inputs here.

**Comment by santhoshvai** [comment] 2022-04-28 11:56
We have updated the documentation at https://getstream.io/chat/docs/sdk/reactnative/guides/push-notifications-v2/. The current documentation clarifies the differences in payload between iOS and Android. 

Furthermore, the documentation in the JS SDK at https://getstream.io/chat/docs/javascript/push_template/?language=javascript has been updated to mention the support of template customization in push V2. We would highly recommend using the template customization feature in the Stream JS SDK to customize your notifications.

I am closing this issue as I believe that the documentation updates clarify the platform limitations and the default payload. Please feel free to reopen this issue or file a new one if you would need any more clarifications.

**Closed by santhoshvai** 2022-04-28 11:56 UTC
