### ISSUE TITLE
Use native context menus for messages

### ISSUE THREAD

**Issue by nandorojo** [GetStream/stream-chat-react-native#2107] opened 2023-05-15 17:11 UTC
**Motivation**

iMessage has really nice long press menus. I notice that stream is trying to somewhat emulate them. However, I think the UX is quite poor and feels non-native on iOS. On Android, the experience is acceptable, but on iOS, I think it should be more tailored to the native menu.

**Proposed solution**

I'd like to propose using the native iOS context menu view on iOS. This can be achieved with [Zeego](https://zeego.dev) or `react-native-ios-context-menu` (which Zeego uses under the hood).

This would also remove the need for `MessageSimple` to double-render by calling `onLayout` inside of `MessageContent`, improving native performance.

**Acceptance Criteria**

Use native context menus rather than JS-based ones.

**Screenshots**

Here's a side-by-side comparison of the two options. The native one looks, in my opinion, way better. It's less laggy, and takes advantage of the platforms' amazing interactions. It's much more familiar to users' expectations on iOS.

| Current (non-native) | Native (with Zeego) |
| --- | --- |
| <video src="https://github.com/GetStream/stream-chat-react-native/assets/13172299/8dea08b5-9de8-43e0-9e2d-3200cff235f5" /> | <video src="https://github.com/GetStream/stream-chat-react-native/assets/13172299/a1434267-6c0d-46af-bbd3-59b8e3382c89" />|

**Added context**

I'm the maintainer of Zeego. I'm working on adding a way to do iMessage-style reactions with a custom view above the message to allow this functionality in Stream

**Comment by andreaslydemann** [comment] 2023-05-16 05:26
+1 for this feature request. A native implementation would give a much smoother UX.

**Comment by nandorojo** [comment] 2023-05-16 20:34
I'll probably implement this myself. However, I'm hoping to find a simple way to read in the `messageActions` and reactions from the parent. It looks like the only way (which I see now) is to fork the `MessageSimple` internals to construct these for the native menu.

**Comment by andreaslydemann** [comment] 2023-05-16 20:49
@nandorojo suppose you can get them from the messagesContext in your child components of <Channel /> like const { supportedReactions, messageActions } = useMessagesContext(); where you can fetch the reactions and message actions

**Comment by nandorojo** [comment] 2023-05-16 21:27
That would be great if it were true. However, from what I see, the API is not that simple.

`messageActions` is either an array, or a function that returns an array and receives all possible actions.

See this logic: https://github.com/GetStream/stream-chat-react-native/blob/d370fef812ceae63ab0a2021d59f56feaad08a89/package/src/components/Message/Message.tsx#L457-L582

**Comment by nandorojo** [comment] 2023-05-16 21:31
I've pulled my hair out a bit trying to figure this out. I'd love to implement it in `MessageSimple`. However, the `messageActions` as a plain array doesn't seem to get exposed anywhere. Instead, it's passed as state to the overlay provider when you long press. I wish there were a `useMessageActions` that accessed context from `Message` or something, which didn't require any arguments.

```tsx
// in message simple...
const messageActions = useMessageActions()
```

**Comment by andreaslydemann** [comment] 2023-05-16 21:46
It seems to be implemented on the message overlay context like const { data: { messageActions } } = useMessageOverlayContext<StreamChatGenerics>();

**Comment by nandorojo** [comment] 2023-05-16 21:53
interesting, i’ll try that. but i believe that is not derived state. rather, it is set by the message item. see the press handler in the code i sent.

**Comment by nandorojo** [comment] 2023-05-16 22:41
Here's a prototype I got working, where I add reactions support via an Auxiliary view (upcoming Zeego feature).

This is **not** using real reactions / messageActions, since these will likely take a few hours to consume properly in a custom message component.

![A4B552E7-B7BF-4EE9-B554-4C15AA65BCE6_1_102_o](https://github.com/GetStream/stream-chat-react-native/assets/13172299/d5a220c6-1751-4d5f-adad-f17847a205ba)

**Comment by andreaslydemann** [comment] 2023-05-16 22:52
Yea I basically got stuck with the same issue trying to get the messageActions without completely dissecting Message.tsx, would likely take some hours and should probably be refactored. The reactions set on `Channel` were fairly straight forward to get though. 

![Skærmoptagelse 2023-05-17 kl  00 47 42](https://github.com/GetStream/stream-chat-react-native/assets/15194614/df6885b3-100d-4573-8361-c5a652ab489d)

**Comment by nandorojo** [comment] 2023-05-16 22:55
cool! you can try the new `ContextMenu.Auxiliary` inside of content if you upgrade zeego. still undocumented, but the types are there.

**Comment by andreaslydemann** [comment] 2023-05-16 23:00
Nice @nandorojo , will try that out!

**Comment by nandorojo** [comment] 2023-05-16 23:07
positioning / sizing is a bit weird, may need to add with and height to the auxiliary itself. the RN iOS context menu lib docs may help, or just playing with the types

**Comment by andreaslydemann** [comment] 2023-05-16 23:52
@nandorojo played around with the auxiliary, really nice addition to zeego! I just came across 2 bugs. 

1. The auxiliary gets smaller and smaller for every time I present the context menu (w/ same message).
2. The auxiliary/reactions list will sometimes be shown at the bottom and the other menu items will appear at the top. Is there a way to enforce the order of the items so the reactions are always above the message?

And also, is there a method I can call to close the menu after choosing a reaction?

![Skærmoptagelse 2023-05-17 kl  01 43 06](https://github.com/GetStream/stream-chat-react-native/assets/15194614/084f0dda-cab1-4fdd-a2ed-8c1b7782fb72)

**Comment by nandorojo** [comment] 2023-05-16 23:54
I believe you need to set fixed height and width on the auxiliary props and let its child adjust accordingly.

I haven't played with the positioning much, but it's possible this is an o option.

**Comment by nandorojo** [comment] 2023-05-16 23:55
i was playing with these props:

```tsx

<ContextMenu.Auxiliary
  transitionEntranceDelay={0}
  transitionConfigEntrance={{
    transition: 'zoomAndSlide',
    // delay: 0,
    // duration: 130,
    slideOffset: 5,

    // options: ['curveEaseInOut'],
  }}
  // anchorPosition='automatic'
  alignmentHorizontal={'previewLeading'}
  width={200}
  height={50}
  marginAuxiliaryPreview={-40}
>
```

the alignment horizontal could be adjusted based on `isMyMessage`

**Comment by andreaslydemann** [comment] 2023-05-17 00:02
Yea alignmentHorizontal={  isMyMessage ? 'previewTrailing' : 'previewLeading' } seems to position it correctly now

**Comment by nandorojo** [comment] 2023-05-17 11:02
Some adjustments I'd like to make: wrap the bubble only, ignoring the time stamp, if possible. I want to remove all spacing around the message itself ideally.

Did you find an easy way to consume the message actions from context?

**Comment by andreaslydemann** [comment] 2023-05-17 11:17
Right now im hiding the time stamp in a custom preview in the context menu like so: 
```<ContextMenu.Preview>
  <StreamChatMessageContent
    MessageFooter={() => null}
    setMessageContentWidth={setMessageContentWidth}
  />
</ContextMenu.Preview>```

And no, haven't found a way to consume the message actions. They are basically determined when pressing down on a message so you can return different sets of actions depending on the pressed message. Guess that is the reason its not so simple to find.

**Comment by vanGalilea** [comment] 2023-05-17 11:28
Hey guys, I see you figured most of it out, you can do the following by overriding `MessageActionList` on `OverlayProvider` see [docs](https://getstream.io/chat/docs/sdk/reactnative/guides/customize-message-actions/#how-to-customize-message-action-ui).

Pseudo code:

```
<OverlayProvider<StreamChatGenerics>
              MessageActionList={(...bla) => {
                const { data } = useMessageOverlayContext<StreamChatGenerics>();

                const { messageActions } = data || {};
                return (
                  <View>
                    {messageActions?.map((ma) => {
                      return (
                        <Pressable
                          onPress={ma.action}
                          style={{
                            flexDirection: 'row',
                            alignItems: 'center',
                            backgroundColor: 'blue',
                          }}
                          s
                        >
                          <Text>{ma.title}</Text>
                          <View>{ma.icon}</View>
                        </Pressable>
                      );
                    })}
                  </View>
                );
              }}
            >
```

**Comment by vanGalilea** [comment] 2023-05-17 11:33
I'll be passing this feature request first to our design team.

Until then, this issue will be moved to an internal backlog list of less urgent feature/docs requests. I'll be closing this issue for now.
Please don't hesitate to contact us in the future if any other questions arise.

You can keep using this closed issue to discuss this customizability further,

**Closed by vanGalilea** 2023-05-17 11:33 UTC
Labels: Feature Request

**Comment by nandorojo** [comment] 2023-05-17 13:16
Hey @vanGalilea! While I appreciate your reply, that actually doesn't address the issue. The native menu handles positioning logic much better, as you can see by the video I shared. It also needs to consume the actions at the `Message` level, since it wraps the message component there, rather than using a JS-based `Overlay`.

The `MessageActionsList` component appears to render within the overlay. I'm hoping to replace the `Overlay` experience altogether and use a native menu which wraps the `Message`.

> Until then, this issue will be moved to an internal backlog list of less urgent feature/docs requests. I'll be closing this issue for now.

Thank you! I appreciate your attention here.

I think there is a somewhat easy way to add this feature without a big rewrite of the library. All I would need is for the final `messageActions` array to get passed as a prop to one of the internal components, such as `MessageContent`. Would this be possible? This way, I could create my own custom component that just maps over an array, rather than re-implementing the entire logic with a fork.

Apologies if that's a confusing explanation, happy to clarify.

I'm also open to submitting a (very minimal!) PR for this if you're open to it. Happy to try to find an easy solution.

**Comment by nandorojo** [comment] 2023-05-17 13:19
> They are basically determined when pressing down on a message so you can return different sets of actions depending on the pressed message. Guess that is the reason its not so simple to find.

This would be easily solved if, rather than constructing the `messageActions` array in the press handler, it was constructed in the render function of the component. This way, it is simply derived state. A single hook could wrap all of this logic into one. I'd be happy to take a stab at it if they're open to it. Otherwise, I'll have to fully implement it myself.

**Comment by andreaslydemann** [comment] 2023-05-17 23:03
@nandorojo that would solve it. That messageActions array from the hook could then be passed down in the message context and accessed by each message.

Btw when using the auxiliary view in zeego, is there a way yet to close the context menu after tapping a reaction?

**Comment by nandorojo** [comment] 2023-05-17 23:20
btw, did you try setting `anchorPosition` to keep it on top? and as for closing when pressing a reaction, i'll have to look into that...

**Comment by nandorojo** [comment] 2023-05-17 23:23
Maybe I could expose an API like this:

```tsx
<ContextMenu.Auxiliary>
  {({ dismiss }) => <Reactions onReact={dismiss} />}
</ContextMenu.Auxiliary>
```

**Comment by andreaslydemann** [comment] 2023-05-17 23:28
Just had a go with anchorPosition, it stays on top now 👍 Its coming together...

**Comment by andreaslydemann** [comment] 2023-05-17 23:31
> Maybe I could expose an API like this:
> 
> 
> 
> ```tsx
> 
> <ContextMenu.Auxiliary>
> 
>   {({ dismiss }) => <Reactions onReact={dismiss} />}
> 
> </ContextMenu.Auxiliary>
> 
> ```

Yup that would be ideal!

**Comment by andreaslydemann** [comment] 2023-05-21 13:10
Made this small message overlay hook for the message actions and the handle reactions method, so the message actions are working on my end now. Still unsure if PRs are accepted for this. @nandorojo you got to look at dismissing context menu when pressing a reaction?

```
import { StreamChatGenerics } from 'chat/types';
import {
  useOwnCapabilitiesContext,
  MessageStatusTypes,
  useTranslationContext,
  useThreadContext,
  useOverlayContext,
  useChannelContext,
  useMessageContext,
  MessageActionListItemProps,
  useMessagesContext,
  messageActions as defaultMessageActions,
  useMessageActions,
  useChatContext,
} from 'stream-chat-expo';

export const useMessageOverlay = () => {
  const { t } = useTranslationContext();
  const ownCapabilities = useOwnCapabilitiesContext();
  const { openThread } = useThreadContext<StreamChatGenerics>();
  const { setOverlay } = useOverlayContext();
  const { channel, enforceUniqueReaction } =
    useChannelContext<StreamChatGenerics>();
  const { client } = useChatContext<StreamChatGenerics>();
  const { message, threadList = false, onOpenThread } = useMessageContext();
  const messagesProps = useMessagesContext();
  const error =
    message.type === 'error' || message.status === MessageStatusTypes.FAILED;
  const isMyMessage = client && message && client.userID === message.user?.id;
  const isThreadMessage = threadList || !!message.parent_id;
  const dismissOverlay = () => setOverlay('none');
  const messageActionsProp =
    messagesProps.messageActions ?? defaultMessageActions;

  const {
    blockUser,
    copyMessage,
    deleteMessage,
    editMessage,
    flagMessage,
    handleReaction,
    muteUser,
    pinMessage,
    quotedReply,
    retry,
    threadReply,
    unpinMessage,
  } = useMessageActions({
    ...messagesProps,
    enforceUniqueReaction,
    channel,
    client,
    message,
    onThreadSelect: onOpenThread,
    openThread,
    setOverlay,
    t,
  });

  const messageActions =
    typeof messageActionsProp !== 'function'
      ? messageActionsProp
      : messageActionsProp({
          blockUser,
          copyMessage,
          deleteMessage,
          dismissOverlay,
          editMessage,
          error,
          flagMessage,
          isMyMessage,
          isThreadMessage,
          message,
          messageReactions: false,
          muteUser,
          ownCapabilities,
          pinMessage,
          quotedReply,
          retry,
          threadReply,
          unpinMessage,
        });

  return {
    handleReaction: ownCapabilities.sendReaction ? handleReaction : undefined,
    messageActions: messageActions
      ? (messageActions?.filter(Boolean) as MessageActionListItemProps[])
      : [],
  };
};
```

**Comment by andreaslydemann** [comment] 2023-05-22 15:40
Here's my code:

```
const MessageContentWithContextMenu = ({
  setMessageContentWidth,
}: {
  setMessageContentWidth: (width: number) => void;
}) => {
  const { messageActions, handleReaction } = useMessageOverlay();
  const { supportedReactions } = useMessagesContext();
  const { isMyMessage } = useMessageContext();

  return (
    <ContextMenu.Root>
      <ContextMenu.Trigger>
        <StreamChatMessageContent
          showMessageStatus={false}
          setMessageContentWidth={setMessageContentWidth}
        />
      </ContextMenu.Trigger>
      <ContextMenu.Content>
        <ContextMenu.Preview>
          <StreamChatMessageContent
            hasReactions={false}
            MessageFooter={() => null}
            setMessageContentWidth={setMessageContentWidth}
          />
        </ContextMenu.Preview>
        <ContextMenu.Auxiliary
          anchorPosition="top"
          transitionEntranceDelay={0}
          transitionConfigEntrance={{
            transition: 'zoomAndSlide',
            slideOffset: 5,
          }}
          alignmentHorizontal={
            isMyMessage ? 'previewTrailing' : 'previewLeading'
          }
          width={245}
          height={50}
        >
          {({ dismissMenu }) => (
            <ReactionList>
              {supportedReactions.map((reaction) => (
                <Reaction
                  key={reaction.type}
                  onPress={() => {
                    handleReaction?.(reaction.type);
                    dismissMenu();
                  }}
                >
                  <reaction.Icon />
                </Reaction>
              ))}
            </ReactionList>
          )}
        </ContextMenu.Auxiliary>
        {messageActions.map((action, index) => (
          <ContextMenu.Item key={index.toString()} onSelect={action.action}>
            <ContextMenu.ItemIcon />
            <ContextMenu.ItemTitle>{action.title}</ContextMenu.ItemTitle>
          </ContextMenu.Item>
        ))}
      </ContextMenu.Content>
    </ContextMenu.Root>
  );
};

export default MessageContentWithContextMenu;

const ReactionList = styled(View)({
  backgroundColor: (p) => p.colors.surface.secondary,
  padding: (p) => p.space.xs,
  flexDirection: 'row',
  borderRadius: 100,
});

const Reaction = styled(Pressable)({
  paddingHorizontal: 4,
});
```

**Comment by nandorojo** [comment] 2023-05-22 15:49
I see…I’m thinking the preview might be layering some sort of z index on top of the auxiliary view. this is likely an issue to open with the upstream ios library. it works fine when there’s no preview, correct?

**Comment by nandorojo** [comment] 2023-05-22 15:50
Also, the children of `Preview` should typically be rendered as a function, per the docs: https://zeego.dev/components/context-menu#preview

Does that change anything?

**Comment by andreaslydemann** [comment] 2023-05-22 16:18
No luck with rendering it as a function... basically only works when there's no preview.

**Comment by nandorojo** [comment] 2023-05-22 16:21
got it, i wonder if there’s anything from react-native-ios-context menu that suggests how to get it to work with a preview. likely requires opening an issue there

**Comment by andreaslydemann** [comment] 2023-05-22 16:23
Yea might be something there, I will look have a look into that library and see what I can find.

**Comment by nandorojo** [comment] 2023-05-23 14:14
Could be worth peaking into the code to see if anything sticks out. I’m sidelining this for a bit since it’s unclear if we’re going to use Sendbird or Stream as we evaluate which is better. But if I end up using Stream, I’ll try to look deeper.

**Comment by andreaslydemann** [comment] 2023-05-23 14:32
For sure, gonna dig a bit deeper on the native side soon. Out of curiosity, how's Sendbird holding up so far? Haven't tried that one at all.

**Comment by nandorojo** [comment] 2023-05-23 14:37
I actually haven’t used it yet. But I’m hoping to find something with a better UI / feel than Stream. So far the UI feels very “React Native”-y to me. So I’m still exploring to see what the best package is to create something that’s up to par with the iMessage experience.

It’s possible I can customize Stream enough, but I want to explore others first. I’m also curious to see if any packages work with FlashList, since it’s a lot faster.

**Comment by andreaslydemann** [comment] 2023-05-23 15:06
I see, curious to hear how well Sendbird holds up... I've more or less gone down the "tweaking" route with many of the components in Stream. The list of packages with expo support is pretty slim, and out of the ones I tried Stream was the more modular one in terms of customizability.

FlashList could be introduced in the MessageList component potentially, might look into that another day.

**Comment by sidorchukandrew** [comment] 2023-07-25 17:47
@nandorojo Have you looked any further into integrating Zeego with Stream? It would be an awesome enhancement.

**Comment by nandorojo** [comment] 2023-07-25 17:53
I haven't, I stopped using Stream for now. Might come back to it in the future if I find the UI more extensible and performant.

**Comment by trymbill** [comment] 2023-09-09 20:47
Found this thread while exploring integrating Zeego with Stream. Out of curiosity, did you end up building something in-house @nandorojo, or did you find a better library?

**Comment by nandorojo** [comment] 2023-09-13 12:53
Not much luck yet. I'd like to pick Stream back up, I just want the UI to be a bit more customizable. If the methods for creating things like menus were moved into more imperative code at the root of the item provider, then it would be simpler.

**Comment by hassannauman** [comment] 2023-11-29 17:38
@andreaslydemann hey! I am using the Auxiliary to display a view for reactions similar to what you have implemented and came across the same issue: reactions not pressable when shows with preview. In your video its shows you commenting the preview yet the message still shows between the options and reactions view. I am trying to implement something similar, can you guide on how to show the preview?

**Comment by dhairyasenjaliya** [comment] 2024-10-21 15:29
Hey @nandorojo above example works well on iOS but I cannot see any item on android any solution for that ?

**Comment by CavalcanteLeo** [comment] 2025-12-11 22:57
https://github.com/user-attachments/assets/d975e9ca-4d5a-4ed9-95b0-57016086d2d0

# ContextMenu.Auxiliary not showing when used with ContextMenu.Preview

## Description

The `ContextMenu.Auxiliary` component from Zeego is not displaying when used alongside `ContextMenu.Preview` on iOS. The auxiliary view should appear above the preview (similar to iMessage reactions), but it's completely absent from the UI.

## Expected Behavior

When long-pressing a message, the context menu should display:
1. The auxiliary view (reactions/complementary view) at the top
2. The preview (message bubble) in the middle
3. The menu action items at the bottom

## Actual Behavior

Only the preview and menu action items are displayed. The auxiliary view is completely missing, even with a simple test view.

## Environment

- **Zeego version**: 3.0.6
- **React Native**: 0.81.5
- **Platform**: iOS 26.1 (iPhone 17 Pro simulator)
- **react-native-ios-context-menu**: 3.2.0
- **react-native-ios-utilities**: 5.2.0

## Code Example


```ts
import { Text } from '@/core/components/Text';
import { REACTION_TYPES } from '@/features/chats/constants/reactions';
import { IcoMoonIconName } from '@/types/icomoon';
import { cn } from '@/utils/cn';
import type { ReactNode } from 'react';
import React, { useMemo } from 'react';
import { Alert, ScrollView, TouchableOpacity, View } from 'react-native';
import type { Message as StreamMessage } from 'stream-chat';
import * as ContextMenu from 'zeego/context-menu';

// Map IcoMoon icon names to SF Symbols (iOS)
const IOS_ICON_MAP: Record<string, string> = {
  share: 'arrowshape.turn.up.left',
  'notification-alarm-ringing': 'bell.badge',
  copy: 'doc.on.doc',
  'reward-flag': 'flag',
  pin: 'pin',
  settings: 'gearshape',
  'trash-bin-1': 'trash',
};

// Map IcoMoon icon names to Material Icons (Android)
const ANDROID_ICON_MAP: Record<string, IcoMoonIconName> = {
  share: 'reply',
  'notification-alarm-ringing': 'notifications',
  copy: 'copy',
  'reward-flag': 'reward-flag',
  pin: 'pin',
  settings: 'settings',
  'trash-bin-1': 'trash-bin-1',
};

function getIosIcon(iconName: string): string {
  return IOS_ICON_MAP[iconName] || 'circle';
}

function getAndroidIcon(iconName: string): string {
  return ANDROID_ICON_MAP[iconName] || 'circle';
}

export interface MessageActions {
  readonly handleReplyPress: () => void;
  readonly handleMarkUnread: () => void;
  readonly handleCopyPress: () => void;
  readonly handleFlagPress: () => void;
  readonly handlePinToggle: () => void;
  readonly handleManageUser: () => void;
  readonly handleDeleteMessage: () => void;
  readonly handleReactionPress: (type: string) => Promise<void>;
  readonly canCopy: boolean;
  readonly canPin: boolean;
  readonly canDelete: boolean;
  readonly isPinned: boolean;
  readonly isAdmin: boolean;
  readonly isOwnMessage: boolean;
}

export interface MessageContentWrapperProps {
  readonly children: ReactNode;
  readonly onLongPress?: () => void;
  readonly messageComponent?: ReactNode;
  readonly messageActions?: MessageActions;
  readonly message?: StreamMessage | null;
  readonly isReadOnlyMessage?: boolean;
  readonly className?: string;
}

export function MessageContentWrapper({
  children,
  messageComponent,
  messageActions,
  message,
  isReadOnlyMessage = false,
  className,
}: MessageContentWrapperProps) {
  if (!messageActions) {
    throw new Error('MessageContentWrapper requires messageActions');
  }

  // Build menu items
  const menuItems = useMemo(() => {
    const items = [];

    if (!isReadOnlyMessage) {
      items.push(
        <ContextMenu.Item
          key="reply"
          onSelect={messageActions.handleReplyPress}
        >
          <ContextMenu.ItemIcon
            ios={{
              name: getIosIcon('share'),
            }}
            androidIconName={getAndroidIcon('share')}
          />
          <ContextMenu.ItemTitle>Reply</ContextMenu.ItemTitle>
        </ContextMenu.Item>,
      );
    }

    items.push(
      <ContextMenu.Item
        key="mark-unread"
        onSelect={messageActions.handleMarkUnread}
      >
        <ContextMenu.ItemIcon
          ios={{
            name: getIosIcon('notification-alarm-ringing'),
          }}
          androidIconName={getAndroidIcon('notification-alarm-ringing')}
        />
        <ContextMenu.ItemTitle>Mark as Unread</ContextMenu.ItemTitle>
      </ContextMenu.Item>,
    );

    if (messageActions.canCopy) {
      items.push(
        <ContextMenu.Item key="copy" onSelect={messageActions.handleCopyPress}>
          <ContextMenu.ItemIcon
            ios={{
              name: getIosIcon('copy'),
            }}
            androidIconName={getAndroidIcon('copy')}
          />
          <ContextMenu.ItemTitle>Copy Message</ContextMenu.ItemTitle>
        </ContextMenu.Item>,
      );
    }

    items.push(
      <ContextMenu.Item key="flag" onSelect={messageActions.handleFlagPress}>
        <ContextMenu.ItemIcon
          ios={{
            name: getIosIcon('reward-flag'),
          }}
          androidIconName={getAndroidIcon('reward-flag')}
        />
        <ContextMenu.ItemTitle>Flag Message</ContextMenu.ItemTitle>
      </ContextMenu.Item>,
    );

    if (messageActions.canPin) {
      items.push(
        <ContextMenu.Item key="pin" onSelect={messageActions.handlePinToggle}>
          <ContextMenu.ItemIcon
            ios={{
              name: getIosIcon('pin'),
            }}
            androidIconName={getAndroidIcon('pin')}
          />
          <ContextMenu.ItemTitle>
            {messageActions.isPinned
              ? 'Unpin from Conversation'
              : 'Pin to Conversation'}
          </ContextMenu.ItemTitle>
        </ContextMenu.Item>,
      );
    }

    if (messageActions.isAdmin && !messageActions.isOwnMessage) {
      items.push(
        <ContextMenu.Item
          key="manage-user"
          onSelect={messageActions.handleManageUser}
        >
          <ContextMenu.ItemIcon
            ios={{
              name: getIosIcon('settings'),
            }}
            androidIconName={getAndroidIcon('settings')}
          />
          <ContextMenu.ItemTitle>Manage User</ContextMenu.ItemTitle>
        </ContextMenu.Item>,
      );
    }

    if (messageActions.canDelete) {
      items.push(
        <ContextMenu.Item
          key="delete"
          destructive
          onSelect={() => {
            Alert.alert(
              'Delete Message',
              'Are you sure you want to delete this message?',
              [
                { text: 'Cancel', style: 'cancel' },
                {
                  text: 'Delete',
                  style: 'destructive',
                  onPress: messageActions.handleDeleteMessage,
                },
              ],
            );
          }}
        >
          <ContextMenu.ItemIcon
            ios={{
              name: getIosIcon('trash-bin-1'),
            }}
            androidIconName={getAndroidIcon('trash-bin-1')}
          />
          <ContextMenu.ItemTitle>Delete Message</ContextMenu.ItemTitle>
        </ContextMenu.Item>,
      );
    }

    return items;
  }, [isReadOnlyMessage, messageActions]);

  // Get reactions from message
  const ownReactions =
    (message as { own_reactions?: { type: string }[] })?.own_reactions || [];

  // Render reactions list for auxiliary view - ALWAYS returns valid React element
  const renderReactionsList = (dismissMenu?: () => void) => {
    return (
      <View
        className="bg-gray-900 items-center justify-center py-2 px-3 w-full h-full rounded-full"
        style={{ minHeight: 50 }}
      >
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 12,
            paddingHorizontal: 4,
          }}
        >
          {REACTION_TYPES.map((reaction) => {
            const hasReaction = message
              ? ownReactions.some(
                  (r: { type: string }) => r.type === reaction.type,
                )
              : false;
            return (
              <TouchableOpacity
                key={reaction.type}
                onPress={() => {
                  if (message) {
                    messageActions.handleReactionPress(reaction.type);
                    dismissMenu?.();
                  }
                }}
                activeOpacity={0.6}
                hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
                className={cn(
                  'size-10 items-center justify-center rounded-full shrink-0',
                  hasReaction ? 'bg-gray-700' : 'bg-transparent',
                )}
              >
                <Text className="text-2xl" pointerEvents="none">
                  {reaction.emoji}
                </Text>
              </TouchableOpacity>
            );
          })}
        </ScrollView>
      </View>
    );
  };

  return (
    <View className={className}>
      <ContextMenu.Root>
        {/* Trigger (Message Bubble) */}
        <ContextMenu.Trigger>{children}</ContextMenu.Trigger>

        <ContextMenu.Content>
          <ContextMenu.Preview>
            <View className="p-2 w-full min-w-[300px] max-w-[90%] max-h-[500px]">
              {messageComponent || (
                <Text className="text-white text-sm">
                  Message preview
                </Text>
              )}
            </View>
          </ContextMenu.Preview>

          <ContextMenu.Auxiliary
            anchorPosition="top"
            alignmentHorizontal={
              messageActions.isOwnMessage ? 'previewTrailing' : 'previewLeading'
            }
            transitionEntranceDelay={0}
            transitionConfigEntrance={{
              transition: 'zoomAndSlide',
              slideOffset: 5,
            }}
            width={280}
            height={60}
          >
            {({ dismissMenu }) => renderReactionsList(dismissMenu)}
          </ContextMenu.Auxiliary>

          {/* Menu Actions Items */}
          {menuItems}
        </ContextMenu.Content>
      </ContextMenu.Root>
    </View>
  );
}
```


Also reported here: https://github.com/nandorojo/zeego/issues/182
