### ISSUE TITLE
Can't run app with OverlayProvider 

### ISSUE THREAD

**Issue by mhsnslymngl** [GetStream/stream-chat-react-native#1696] opened 2022-09-01 12:01 UTC
When I try to import OverlayProvider, the app gives an error

![image](https://user-images.githubusercontent.com/18623102/187908921-46e73ec0-b0a7-4cb8-afb0-16d261b70e9b.png)
![image](https://user-images.githubusercontent.com/18623102/187909038-b544b3e6-89d9-4eda-82c5-4dc45ba7385b.png)

**Comment by madsroskar** [comment] 2022-09-01 13:47
With expo, you should have `stream-chat-expo` installed and use that instead of `stream-chat-react-native`. 

I can't reproduce this issue on my end. Could you create a minimal reproduction of the issue in a repo, and share that with me?

**Comment by khushal87** [comment] 2022-09-05 07:43
@mhsnslymngl Does the above solution by @madsroskar help you? I think import using stream-chat-expo should work.

If this works, please let us know so that we can go ahead with closing the ticket.

**Closed** 2022-09-05 17:50 UTC
Labels: Needs Triaging
