### ISSUE TITLE
Android crash after long press on message

### ISSUE THREAD

**Issue by kitraweewjv** [GetStream/stream-chat-react-native#1683] opened 2022-08-26 11:21 UTC
**Describe the bug**
When I press a long press on a message in the chat to see the actions (delete, etc),

**Dev environment info:**

- Package version (stream-chat-react-native/stream-chat-expo)
````
"stream-chat-react-native": "^3.9.0"
"@react-native-community/blur": "^3.6.0"
"@stream-io/flat-list-mvcp": "^0.10.2"
"react-native-reanimated": "^2.2.3"
````
- react-native or expo version
````
"react-native": "^0.66.0"
````

**To Reproduce**

1. Build Android
2. Open channel screen
3. Long press on message
4. App crash

**Additional context**
- I already add this code in app.tsx
````
registerNativeHandlers({
  BlurView: () => (
    <View style={[StyleSheet.absoluteFillObject, {backgroundColor: 'red'}]} />
  ),
});
````
- Log samples:
````
FATAL EXCEPTION: main
Process: com.wjames.wirtual, PID: 6187
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.facebook.react.bridge.JavaOnlyArray.getDouble(JavaOnlyArray.java:91)
	at com.horcrux.svg.RenderableView.setupPaint(RenderableView.java:491)
	at com.horcrux.svg.RenderableView.setupFillPaint(RenderableView.java:436)
	at com.horcrux.svg.RenderableView.draw(RenderableView.java:374)
	at com.horcrux.svg.RenderableView.render(RenderableView.java:340)
	at com.horcrux.svg.GroupView.drawGroup(GroupView.java:104)
	at com.horcrux.svg.GroupView.draw(GroupView.java:81)
	at com.horcrux.svg.RenderableView.render(RenderableView.java:340)
	at com.horcrux.svg.SvgView.drawChildren(SvgView.java:310)
	at com.horcrux.svg.SvgView.drawOutput(SvgView.java:261)
	at com.horcrux.svg.SvgView.onDraw(SvgView.java:107)
	at android.view.View.draw(View.java:22704)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.View.draw(View.java:22435)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
	at android.view.View.updateDisplayListIfDirty(View.java:21570)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4525)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4245)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
````

**Comment by madsroskar** [comment] 2022-08-30 13:12
Hi @kitraweewjv.

While I would recommend upgrading to version 4.x where BlurView isn't a listed dependency, we have a troubleshooting step in our 3.x documentation that might help you with this issue:

https://getstream.io/chat/docs/sdk/reactnative/v3/basics/troubleshooting/#blurview-crashing

Could you try this, and see if it helps you with this crash?

**Comment by khushal87** [comment] 2022-09-05 12:32
Hey @kitraweewjv, is your issue resolved now after upgrading to 4.x or using the guide mentioned above? If not, please let us know. Also, if it is resolved, kindly close this. Thanks 😄

**Comment by vishalnarkhede** [comment] 2022-09-10 16:46
We would recommend upgrading to v5 instead of v4, since thats the latest release and currently being maintained.

**Closed** 2022-09-13 08:32 UTC
Labels: Needs Triaging

**Comment by gregssdev** [comment] 2022-11-15 16:52
Still same issue

On Android when you type some message, a long message it will freeze the app at a random interval of time

Package version (stream-chat-react-native): 5.0.0
react-native: 0.66.3
Device (android): Any

Steps to reproduce the behavior:
Go to Message Input
Type something random around 100-200 words
If the app didn't freeze, clear a few words and start typing again for a while
App will freeze

Expected behavior
App should run smoothly
