### ISSUE TITLE
Block quote and nested list markdown styling is not working

### ISSUE THREAD

**Issue by khushal87** [GetStream/stream-chat-react-native#1423] opened 2022-05-31 11:57 UTC
**Motivation**
Ref - https://getstream.zendesk.com/agent/tickets/23105
The customer would like to have styling for the nested list as well as blockquote in his/her application. 

**Proposed solution**
The `renderText` function doesn't have the styling for blockquote and possibly the nested list. Therefore we plan to add default styles so that we can ship them to our customers. Moreover, we plan to customize the `MessageTextContainer` component which will improve the use case for the same. Find it #1381

**Acceptance Criteria**
- Default styling for blockquote and nested lists is implemented.
- Can be overridden by the `markdownStyles` prop.

**Comment by vanGalilea** [comment] 2022-06-21 08:12
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/React-Native-SDK-62285abeb7c8e800229effc5/issues/GetStream/stream-chat-react-native/1423?planning-poker) with ZenHub @Enigma-I-am @khushal87 @madsroskar @vishalnarkhede @santhoshvai

**Comment by santhoshvai** [comment] 2022-08-19 20:41
Duplicate of #1667 which has more info and additional info. Hence closing this.

**Closed by santhoshvai** 2022-08-19 20:41 UTC
Labels: Feature Request
