### ISSUE TITLE
Web <> Mobile Reactions are not compatible

### ISSUE THREAD

**Issue by TaharS** [GetStream/stream-chat-react-native#2023] opened 2023-03-23 17:27 UTC
**Describe the bug**
Our applications leverage the whole Stream suite - Mobile and Web. Our users are cross-platform and we give access to messaging via Stream to all of them.
The issue we are seeing here is that Reactions are actually not synced between mobile and web
The culprit of this, is simply how the data is stored:

<img width="1063" alt="Screen Shot 2023-03-23 at 10 10 27 AM" src="https://user-images.githubusercontent.com/10080564/227286184-fa322395-d070-4ff1-ba88-d7e74deb22cd.png">

Is this intended behaviour? 

**Dev environment info (please complete/provide the following information):**

- Package version
```
    "stream-chat": "8.2.1",
    "stream-chat-react-native": "^5.11.2",
```
- react-native or expo version
```
    "react-native": "0.70.3",
```
- Device/Emulator (android/ios) and OS version
- Android Emulator Pixel 5 API 33/iOS iPhone 14 Pro Max iOS 16

**To Reproduce**

1. Open a mobile application and add a reaction
2. Open a web application with the same conversation
3. Observe reactions on web
4. From the web application apply a 👍 emoji
5. Observe reactions on mobile

**Expected behavior**
Reactions should be showing cross platform

**Additional context**
n/a

**Screenshots**
n/a

**Comment by khushal87** [comment] 2023-03-24 06:02
Hey @TaharS, we couldn't reproduce this behaviour on our side after a couple of attempts. Sharing a video on how it works on our side. I would like to know if you are adding in customization or modifying some behaviour.

https://user-images.githubusercontent.com/39884168/227437521-4f8115a9-da2d-4561-8dba-608b74672fce.mov

**Comment by nandorojo** [comment] 2023-05-22 14:06
@TaharS did this end up getting fixed for you? Just wondering what the status is, as I've faced some web & mobile inconsistencies with unread messages as well.

**Comment by TaharS** [comment] 2023-05-22 19:34
> @TaharS did this end up getting fixed for you? Just wondering what the status is, as I've faced some web & mobile inconsistencies with unread messages as well.

Hey @nandorojo, so if we talk about the reactions here, we cut scope and removed the custom work. Therefore we went with the out of the box reaction on both mobile/web. They work well on that side
We haven't had any issues/inconsistencies with unread messages to this date.

https://github.com/GetStream/stream-chat-react/pull/1947 seems to be in the work to have a better custom reaction experience? Not really sure there though

**Comment by vanGalilea** [comment] 2023-05-24 07:38
The issue is solved and I'll be closing this issue for now.
Please don't hesitate to contact us in the future if this issue or any questions arise.

**Closed by vanGalilea** 2023-05-24 07:38 UTC
Labels: Awaiting Confirmation

**Comment by tanishadandona** [comment] 2023-06-26 13:20
I want to Customize message Reactions  . how to do this?
