### ISSUE TITLE
Bug in Gallery in right to left orientation

### ISSUE THREAD

**Issue by RomanBob123** [GetStream/stream-chat-react-native#1007] opened 2021-11-19 08:37 UTC
When I switch app localization to rtl (like Hebrew or Arabic), when I try to view images in full screen size, I get this error.
Pictures are not displayed, caption below with an error.

![Screenshot from 2021-11-17 17-22-25](https://user-images.githubusercontent.com/91616406/142591793-254ad717-3f01-41f2-bff9-01e945ff01cb.png)

gz#16880

**Comment by madsroskar** [comment] 2021-11-19 18:46
Thanks for raising the issue, @RomanBob123. Do you get any errors in the console at all when this happens?

**Comment by RomanBob123** [comment] 2021-11-22 13:06
@madsroskar There are no errors in the console

**Comment by vishalnarkhede** [comment] 2021-11-23 10:16
Hey @RomanBob123 we would appreciate some help reproducing this issue.

How do you switch the app localization in your codebase or application? I tried switching device language to hebrew but couldn't reproduce this issue. I am guessing that you have provided some translations for the keys using our [internationalization](https://getstream.io/chat/docs/sdk/reactnative/basics/translations/) system. If you can provide the code around this implementation, that would be great :)

**Comment by vishalnarkhede** [comment] 2021-12-09 10:22
@RomanBob123 ping ^^

**Comment by RomanBob123** [comment] 2022-01-05 08:47
@vishalnarkhede Sorry for delay. I fixed the translation problem, it was on our side. Because of custom translations. But the error still persisted in the gallery. Pictures are simply not displayed in RTL. In order for this to be played, try to set
```
I18nManager.forceRTL(true);
I18nManager.allowRTL(true);
```

**Comment by mohofo7** [comment] 2022-01-25 14:15
I had the same problem here, so I open a [PR](#1112).

After that, we can change flex-direction of the pager to row-reverse, and change slide margins.

with these changes, ImageGallery works fine with Right to Left

**Comment by vishalnarkhede** [comment] 2022-04-05 12:10
Hey @RomanBob123 please check the solution suggested by @mohofo7 !! The PR has been merged and released as part of `v4.1.1`!!

**Closed by vishalnarkhede** 2022-04-05 12:10 UTC
Labels: Needs More Information, Needs Triaging
